# Generated by Django 6.0.2 on 2026-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Adonis Group', max_length=100, verbose_name='Company Name')),
                ('description', models.TextField(default='Your trusted partner for Greek residency and smart investment. Built on experience, driven by trust, focused on your future in Europe.', verbose_name='Footer Description')),
                ('copyright_text', models.CharField(blank=True, help_text='Leave blank for default: "© {year} Company Name. All rights reserved."', max_length=200, verbose_name='Copyright Text')),
                ('address', models.TextField(default='Athens, Alimos, Poseidonos Avenue, No. 78, 1st Floor', verbose_name='Address')),
                ('phone_number', models.CharField(default='+306985989596', max_length=20, verbose_name='Phone / WhatsApp')),
                ('email', models.EmailField(default='info@adonisgroup.gr', max_length=254, verbose_name='Email')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('whatsapp_number', models.CharField(default='+306985989596', help_text='WhatsApp number for footer chat button', max_length=20, verbose_name='WhatsApp Number')),
                ('whatsapp_button_text', models.CharField(default='Chat Now', max_length=50, verbose_name='WhatsApp Button Text')),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Adonis Group', help_text='Displayed when no logo is uploaded', max_length=100, verbose_name='Site Name')),
                ('logo', models.ImageField(blank=True, help_text='Upload site logo (recommended: transparent PNG, max height 60px)', null=True, upload_to='header/', verbose_name='Logo')),
                ('logo_width', models.PositiveIntegerField(default=160, help_text='Logo display width in pixels', verbose_name='Logo Width (px)')),
                ('logo_height', models.PositiveIntegerField(default=50, help_text='Logo display height in pixels', verbose_name='Logo Height (px)')),
                ('whatsapp_number', models.CharField(default='+306985989596', help_text='WhatsApp number with country code (e.g. +306985989596)', max_length=20, verbose_name='WhatsApp Number')),
                ('contact_button_text', models.CharField(default='Contact Us', help_text='Text shown on the green WhatsApp button in header', max_length=50, verbose_name='Contact Button Text')),
                ('show_home', models.BooleanField(default=True, verbose_name='Show Home')),
                ('show_properties', models.BooleanField(default=True, verbose_name='Show Properties')),
                ('show_partnerships', models.BooleanField(default=True, verbose_name='Show Partnerships')),
                ('show_about', models.BooleanField(default=True, verbose_name='Show About')),
                ('show_contact', models.BooleanField(default=True, verbose_name='Show Contact')),
            ],
            options={
                'verbose_name': 'Header Settings',
                'verbose_name_plural': 'Header Settings',
            },
        ),
    ]
