# Generated by Django 6.0.2 on 2026-02-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_footersettings_headersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='hero_subtitle',
            field=models.TextField(default='Permanent residency for your family by purchasing property in Greece | Official offices in Athens', help_text='Sub-heading text below the title', verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='hero_title',
            field=models.CharField(default='Greek Residency', help_text='Main heading text in hero section', max_length=200, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Upload a background video for the hero section (MP4 recommended, max 30MB)', null=True, upload_to='hero/', verbose_name='Hero Video'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='hero_video_poster',
            field=models.ImageField(blank=True, help_text='Fallback image shown while video loads or on mobile', null=True, upload_to='hero/', verbose_name='Video Poster Image'),
        ),
    ]
