# Generated by Django 6.0.2 on 2026-02-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_headersettings_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='hero_brightness',
            field=models.PositiveIntegerField(default=100, help_text='Video brightness (100=normal, lower=darker, higher=brighter)', verbose_name='Video Brightness (%)'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='hero_filter',
            field=models.CharField(choices=[('none', 'None'), ('grayscale', 'Grayscale (black & white)'), ('sepia', 'Sepia (warm vintage)'), ('blur', 'Blur (soft focus)'), ('saturate', 'Saturate (vivid colors)'), ('contrast', 'High Contrast'), ('brightness-up', 'Brighter'), ('brightness-down', 'Darker')], default='none', help_text='CSS filter applied to the video', max_length=20, verbose_name='Video Filter'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='hero_overlay',
            field=models.CharField(choices=[('dark', 'Dark (dark blue overlay)'), ('light', 'Light (semi-transparent white)'), ('gradient', 'Gradient (blue gradient)'), ('none', 'None (no overlay)')], default='dark', help_text='Type of overlay on top of the video', max_length=20, verbose_name='Video Overlay'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='hero_overlay_opacity',
            field=models.PositiveIntegerField(default=50, help_text='Overlay darkness/lightness (0=transparent, 100=fully opaque)', verbose_name='Overlay Opacity (%)'),
        ),
    ]
