# Generated by Django 6.0.2 on 2026-02-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_headersettings_hero_brightness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_font', models.CharField(choices=[('Playfair Display', 'Playfair Display (elegant serif)'), ('Inter', 'Inter (clean sans-serif)'), ('Roboto', 'Roboto'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Lora', 'Lora (classic serif)'), ('Raleway', 'Raleway'), ('Open Sans', 'Open Sans'), ('Nunito', 'Nunito')], default='Playfair Display', max_length=50, verbose_name='Heading Font')),
                ('body_font', models.CharField(choices=[('Playfair Display', 'Playfair Display (elegant serif)'), ('Inter', 'Inter (clean sans-serif)'), ('Roboto', 'Roboto'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Lora', 'Lora (classic serif)'), ('Raleway', 'Raleway'), ('Open Sans', 'Open Sans'), ('Nunito', 'Nunito')], default='Inter', max_length=50, verbose_name='Body Font')),
                ('heading_size', models.PositiveIntegerField(default=100, help_text='100 = default. e.g. 120 = 20% bigger', verbose_name='Heading Size (%)')),
                ('body_size', models.PositiveIntegerField(default=16, help_text='Default is 16px', verbose_name='Body Font Size (px)')),
                ('services_badge', models.CharField(default='Why Choose Us', max_length=100, verbose_name='Services Badge Text')),
                ('services_title', models.CharField(default='Golden Visa & Greek Passport', max_length=200, verbose_name='Services Title')),
                ('services_description', models.TextField(default='With a minimum investment of €250,000 in Greek real estate, you can obtain permanent residency in Europe and, over time, a high-ranking Greek passport.', verbose_name='Services Description')),
                ('services_image', models.ImageField(blank=True, help_text='Optional background image for services section', null=True, upload_to='frontpage/', verbose_name='Services Section Image')),
                ('process_badge', models.CharField(default='How It Works', max_length=100, verbose_name='Process Badge Text')),
                ('process_title', models.CharField(default='Residency Process in Greece', max_length=200, verbose_name='Process Title')),
                ('process_description', models.TextField(default='Fast, Guaranteed & Recommended - Our streamlined process ensures your success', verbose_name='Process Description')),
                ('properties_badge', models.CharField(default='Investment Opportunities', max_length=100, verbose_name='Properties Badge')),
                ('properties_title', models.CharField(default='Featured Properties for Greek Residency', max_length=200, verbose_name='Properties Title')),
                ('properties_description', models.TextField(default='Luxury living in the heart of Athens - carefully selected properties for Golden Visa eligibility', verbose_name='Properties Description')),
                ('cta_title', models.CharField(default='Discover Our Developer-Led Investment Opportunities', max_length=200, verbose_name='CTA Title')),
                ('cta_description', models.TextField(default='Download our latest investment catalog featuring exclusive residential projects developed and delivered directly by our team.', verbose_name='CTA Description')),
                ('cta_button_text', models.CharField(default='Download the Catalog', max_length=100, verbose_name='CTA Button Text')),
                ('cta_image', models.ImageField(blank=True, null=True, upload_to='frontpage/', verbose_name='CTA Background Image')),
                ('contact_badge', models.CharField(default='Get In Touch', max_length=100, verbose_name='Contact Badge')),
                ('contact_title', models.CharField(default='Book a Free Consultation', max_length=200, verbose_name='Contact Title')),
                ('contact_description', models.TextField(default='Fill out the form and our expert advisors will guide you through the process step by step, with clear answers to all your questions.', verbose_name='Contact Description')),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='frontpage/gallery/', verbose_name='Gallery Image 1')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='frontpage/gallery/', verbose_name='Gallery Image 2')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='frontpage/gallery/', verbose_name='Gallery Image 3')),
                ('gallery_image_4', models.ImageField(blank=True, null=True, upload_to='frontpage/gallery/', verbose_name='Gallery Image 4')),
                ('promo_video', models.FileField(blank=True, help_text='Optional promotional video (MP4)', null=True, upload_to='frontpage/', verbose_name='Promo Video')),
            ],
            options={
                'verbose_name': 'Front Page Settings',
                'verbose_name_plural': 'Front Page Settings',
            },
        ),
    ]
