# Generated by Django 6.0.2 on 2026-02-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_frontpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagesettings',
            name='body_color',
            field=models.CharField(default='#475569', help_text='Hex color code e.g. #475569', max_length=7, verbose_name='Body Text Color'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='body_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic')], default='normal', max_length=10, verbose_name='Body Style (Italic)'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='body_weight',
            field=models.CharField(choices=[('300', 'Light (300)'), ('400', 'Regular (400)'), ('500', 'Medium (500)'), ('600', 'Semi-Bold (600)'), ('700', 'Bold (700)'), ('800', 'Extra-Bold (800)'), ('900', 'Black (900)')], default='400', max_length=5, verbose_name='Body Weight (Bold)'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='heading_color',
            field=models.CharField(default='#0D5EAF', help_text='Hex color code e.g. #0D5EAF', max_length=7, verbose_name='Heading Color'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='heading_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic')], default='normal', max_length=10, verbose_name='Heading Style (Italic)'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='heading_weight',
            field=models.CharField(choices=[('300', 'Light (300)'), ('400', 'Regular (400)'), ('500', 'Medium (500)'), ('600', 'Semi-Bold (600)'), ('700', 'Bold (700)'), ('800', 'Extra-Bold (800)'), ('900', 'Black (900)')], default='600', max_length=5, verbose_name='Heading Weight (Bold)'),
        ),
        migrations.AlterField(
            model_name='frontpagesettings',
            name='body_font',
            field=models.CharField(choices=[('Playfair Display', 'Playfair Display (elegant serif)'), ('Lora', 'Lora (classic serif)'), ('Merriweather', 'Merriweather (readable serif)'), ('Cormorant Garamond', 'Cormorant Garamond (luxury serif)'), ('Libre Baskerville', 'Libre Baskerville (traditional)'), ('EB Garamond', 'EB Garamond (classic book)'), ('Crimson Text', 'Crimson Text (warm serif)'), ('DM Serif Display', 'DM Serif Display (modern serif)'), ('Noto Serif', 'Noto Serif'), ('Inter', 'Inter (clean sans-serif)'), ('Roboto', 'Roboto'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Raleway', 'Raleway'), ('Open Sans', 'Open Sans'), ('Nunito', 'Nunito'), ('Lato', 'Lato'), ('Source Sans 3', 'Source Sans 3'), ('DM Sans', 'DM Sans (modern)'), ('Manrope', 'Manrope (geometric)'), ('Plus Jakarta Sans', 'Plus Jakarta Sans (trendy)'), ('Outfit', 'Outfit (clean modern)'), ('Space Grotesk', 'Space Grotesk (tech feel)'), ('Figtree', 'Figtree (friendly)'), ('Oswald', 'Oswald (condensed)'), ('Bebas Neue', 'Bebas Neue (bold display)'), ('Abril Fatface', 'Abril Fatface (elegant display)'), ('Josefin Sans', 'Josefin Sans (stylish)'), ('Noto Sans Arabic', 'Noto Sans Arabic'), ('Cairo', 'Cairo (Arabic-friendly)'), ('Tajawal', 'Tajawal (Arabic-friendly)')], default='Inter', max_length=50, verbose_name='Body Font'),
        ),
        migrations.AlterField(
            model_name='frontpagesettings',
            name='heading_font',
            field=models.CharField(choices=[('Playfair Display', 'Playfair Display (elegant serif)'), ('Lora', 'Lora (classic serif)'), ('Merriweather', 'Merriweather (readable serif)'), ('Cormorant Garamond', 'Cormorant Garamond (luxury serif)'), ('Libre Baskerville', 'Libre Baskerville (traditional)'), ('EB Garamond', 'EB Garamond (classic book)'), ('Crimson Text', 'Crimson Text (warm serif)'), ('DM Serif Display', 'DM Serif Display (modern serif)'), ('Noto Serif', 'Noto Serif'), ('Inter', 'Inter (clean sans-serif)'), ('Roboto', 'Roboto'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Raleway', 'Raleway'), ('Open Sans', 'Open Sans'), ('Nunito', 'Nunito'), ('Lato', 'Lato'), ('Source Sans 3', 'Source Sans 3'), ('DM Sans', 'DM Sans (modern)'), ('Manrope', 'Manrope (geometric)'), ('Plus Jakarta Sans', 'Plus Jakarta Sans (trendy)'), ('Outfit', 'Outfit (clean modern)'), ('Space Grotesk', 'Space Grotesk (tech feel)'), ('Figtree', 'Figtree (friendly)'), ('Oswald', 'Oswald (condensed)'), ('Bebas Neue', 'Bebas Neue (bold display)'), ('Abril Fatface', 'Abril Fatface (elegant display)'), ('Josefin Sans', 'Josefin Sans (stylish)'), ('Noto Sans Arabic', 'Noto Sans Arabic'), ('Cairo', 'Cairo (Arabic-friendly)'), ('Tajawal', 'Tajawal (Arabic-friendly)')], default='Playfair Display', max_length=50, verbose_name='Heading Font'),
        ),
    ]
