# Generated by Django 6.0.2 on 2026-02-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_frontpagesettings_body_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Your Trusted Partner for Greek Residency', max_length=200, verbose_name='Hero Title')),
                ('hero_subtitle', models.TextField(default='Built on experience, driven by trust, focused on your future in Europe', verbose_name='Hero Subtitle')),
                ('office_video', models.FileField(blank=True, help_text='Upload a video showcasing the office (MP4 recommended)', null=True, upload_to='about/', verbose_name='Office Video')),
                ('office_video_poster', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Video Poster Image')),
                ('office_image_1', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Office Image 1')),
                ('office_image_2', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Office Image 2')),
                ('office_image_3', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Office Image 3')),
                ('about_title', models.CharField(default='Who We Are', max_length=200, verbose_name='About Section Title')),
                ('about_text', models.TextField(default='At Adonis Group, we carefully select the finest locations in Athens to create residential projects that combine modern design, comfort, and investment security.', help_text='Main about us text. HTML allowed.', verbose_name='About Text')),
                ('team_title', models.CharField(default='Our Team', max_length=100, verbose_name='Team Section Title')),
                ('team_subtitle', models.TextField(blank=True, default='Meet the professionals behind Adonis Group', verbose_name='Team Subtitle')),
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('position', models.CharField(max_length=100, verbose_name='Position / Title')),
                ('photo', models.ImageField(blank=True, help_text='Square photo recommended (400x400px)', null=True, upload_to='team/', verbose_name='Photo')),
                ('bio', models.TextField(blank=True, verbose_name='Short Bio')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
    ]
