# Generated by Django 6.0.2 on 2026-02-06 20:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aboutpagesettings_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagesettings',
            name='about_text',
            field=ckeditor.fields.RichTextField(default='<p>At Adonis Group, we carefully select the finest locations in Athens to create residential projects that combine modern design, comfort, and investment security.</p>', help_text='Main about us text. You can use formatting here.', verbose_name='About Text'),
        ),
    ]
