# Generated by Django 6.0.2 on 2026-02-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aboutpagesettings_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('address', models.TextField(verbose_name='Full Address')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('map_embed_url', models.TextField(help_text='Full iframe embed URL from Google Maps', verbose_name='Google Maps Embed URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Office Location',
                'verbose_name_plural': 'Office Locations',
                'ordering': ['order'],
            },
        ),
    ]
