# Generated by Django 6.0.2 on 2026-02-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='intro_text',
            field=models.TextField(default='At Adonis Group, we specialize in helping international investors and families secure their Greek Golden Visa through strategic real estate investments. With offices in Athens and Tehran, our multilingual team provides end-to-end support—from property selection to residency approval.', help_text='Description text next to the intro video', verbose_name='Intro Text'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='intro_title',
            field=models.CharField(default='Welcome to Adonis Group', help_text='Title displayed next to the intro video', max_length=200, verbose_name='Intro Title'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='intro_video',
            field=models.FileField(blank=True, help_text='Upload a video for the intro section below hero (MP4 recommended)', null=True, upload_to='intro/', verbose_name='Intro Video'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='intro_video_poster',
            field=models.ImageField(blank=True, help_text='Thumbnail image shown before video plays', null=True, upload_to='intro/', verbose_name='Intro Video Poster'),
        ),
    ]
