# Generated by Django 6.0.2 on 2026-02-06 21:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_headersettings_intro_text_headersettings_intro_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='URL-friendly version of title (auto-generated)', unique=True, verbose_name='URL Slug')),
                ('excerpt', models.TextField(help_text='Short summary shown in blog list (max 300 chars)', max_length=300, verbose_name='Excerpt / Summary')),
                ('content', ckeditor.fields.RichTextField(help_text='Full blog post content', verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, help_text='Main image for the blog post (recommended: 1200x630px for social sharing)', null=True, upload_to='blog/', verbose_name='Featured Image')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alternative text for SEO and accessibility', max_length=200, verbose_name='Image Alt Text')),
                ('meta_title', models.CharField(blank=True, help_text='Title for search engines (max 70 chars). Leave blank to use post title.', max_length=70, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, help_text='Description for search engines (max 160 chars). Leave blank to use excerpt.', max_length=160, verbose_name='SEO Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=200, verbose_name='SEO Keywords')),
                ('canonical_url', models.URLField(blank=True, help_text='Leave blank for default URL', verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, help_text='Title for social media sharing', max_length=100, verbose_name='Social Title')),
                ('og_description', models.CharField(blank=True, help_text='Description for social media sharing', max_length=200, verbose_name='Social Description')),
                ('author', models.CharField(default='Adonis Group', max_length=100, verbose_name='Author')),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
