# Generated by Django 6.0.2 on 2026-02-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Bot token from @BotFather (e.g. 123456:ABC-DEF...)', max_length=100, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Chat/Group ID to send notifications to. Use @userinfobot to find your ID.', max_length=100, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_enabled',
            field=models.BooleanField(default=False, help_text='Send contact form submissions to Telegram', verbose_name='Enable Telegram Notifications'),
        ),
    ]
