# Generated by Django 6.0.2 on 2026-02-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('topic', models.CharField(blank=True, max_length=200, verbose_name='Topic / Interest')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='Page URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Chat Lead',
                'verbose_name_plural': 'Chat Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
