# Generated by Django 6.0.1 on 2026-02-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chatlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Partner With Adonis Group', max_length=200, verbose_name='Hero Title')),
                ('hero_subtitle', models.TextField(default='Join our exclusive network of real estate professionals and unlock new opportunities in the Greek Golden Visa market.', verbose_name='Hero Subtitle')),
                ('hero_image', models.ImageField(blank=True, help_text='Background image for the hero section', null=True, upload_to='partnership/', verbose_name='Hero Background Image')),
                ('video', models.FileField(blank=True, help_text='Upload a video (MP4, max 1:30 min)', null=True, upload_to='partnership/', verbose_name='Partnership Video')),
                ('video_cover', models.ImageField(blank=True, help_text='Cover/poster image shown before video plays', null=True, upload_to='partnership/', verbose_name='Video Cover Image')),
                ('video_title', models.CharField(blank=True, default='Discover Our Partnership Program', max_length=200, verbose_name='Video Section Title')),
                ('video_subtitle', models.TextField(blank=True, default='Watch how our partners grow their business with Adonis Group.', verbose_name='Video Section Subtitle')),
                ('b2b_title', models.CharField(default='Why B2B With Adonis Group?', max_length=200, verbose_name='B2B Section Title')),
                ('b2b_text', models.TextField(default='Adonis Group offers a unique opportunity for real estate professionals...', help_text='Main text explaining why businesses should partner with Adonis', verbose_name='B2B Description')),
                ('b2b_image', models.ImageField(blank=True, null=True, upload_to='partnership/', verbose_name='B2B Section Image')),
                ('benefit_1_icon', models.CharField(default='fas fa-percentage', max_length=50, verbose_name='Benefit 1 Icon')),
                ('benefit_1_title', models.CharField(default='Competitive Commission', max_length=100, verbose_name='Benefit 1 Title')),
                ('benefit_1_text', models.TextField(default='Earn attractive commissions on every successful referral and sale.', verbose_name='Benefit 1 Text')),
                ('benefit_2_icon', models.CharField(default='fas fa-building', max_length=50, verbose_name='Benefit 2 Icon')),
                ('benefit_2_title', models.CharField(default='Exclusive Inventory', max_length=100, verbose_name='Benefit 2 Title')),
                ('benefit_2_text', models.TextField(default='Access to premium properties not available on the open market.', verbose_name='Benefit 2 Text')),
                ('benefit_3_icon', models.CharField(default='fas fa-headset', max_length=50, verbose_name='Benefit 3 Icon')),
                ('benefit_3_title', models.CharField(default='Dedicated Support', max_length=100, verbose_name='Benefit 3 Title')),
                ('benefit_3_text', models.TextField(default='Full support from our team throughout the entire sales process.', verbose_name='Benefit 3 Text')),
                ('benefit_4_icon', models.CharField(default='fas fa-graduation-cap', max_length=50, verbose_name='Benefit 4 Icon')),
                ('benefit_4_title', models.CharField(default='Training & Resources', max_length=100, verbose_name='Benefit 4 Title')),
                ('benefit_4_text', models.TextField(default='Comprehensive training materials and marketing resources.', verbose_name='Benefit 4 Text')),
                ('benefit_5_icon', models.CharField(default='fas fa-globe', max_length=50, verbose_name='Benefit 5 Icon')),
                ('benefit_5_title', models.CharField(default='Global Network', max_length=100, verbose_name='Benefit 5 Title')),
                ('benefit_5_text', models.TextField(default='Join our international network of real estate professionals.', verbose_name='Benefit 5 Text')),
                ('benefit_6_icon', models.CharField(default='fas fa-chart-line', max_length=50, verbose_name='Benefit 6 Icon')),
                ('benefit_6_title', models.CharField(default='Growth Opportunity', max_length=100, verbose_name='Benefit 6 Title')),
                ('benefit_6_text', models.TextField(default='Expand your business with the growing Golden Visa market.', verbose_name='Benefit 6 Text')),
                ('cta_title', models.CharField(default='Ready to Become a Partner?', max_length=200, verbose_name='CTA Title')),
                ('cta_text', models.TextField(default='Contact us today to learn more about our partnership program and start earning.', verbose_name='CTA Text')),
                ('cta_button_text', models.CharField(default='Become a Partner', max_length=50, verbose_name='CTA Button Text')),
            ],
            options={
                'verbose_name': 'Partnership Page',
                'verbose_name_plural': 'Partnership Page',
            },
        ),
    ]
