# Generated by Django 6.0.1 on 2026-02-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_partnershippagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertiesPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Adonis Residential Developments', max_length=200, verbose_name='Hero Title')),
                ('hero_subtitle', models.TextField(default='With property investment in Greece, you can both invest and secure permanent residency in Europe', verbose_name='Hero Subtitle')),
                ('hero_badge', models.CharField(default='Investment Opportunities', max_length=100, verbose_name='Hero Badge Text')),
                ('hero_video', models.FileField(blank=True, help_text='Upload a background video for the hero section (MP4 recommended, max 30MB)', null=True, upload_to='properties/', verbose_name='Hero Video')),
                ('hero_video_poster', models.ImageField(blank=True, help_text='Fallback image shown while video loads or on mobile', null=True, upload_to='properties/', verbose_name='Video Poster Image')),
                ('hero_image', models.ImageField(blank=True, help_text='Background image if no video is uploaded', null=True, upload_to='properties/', verbose_name='Hero Background Image')),
                ('intro_title', models.CharField(default='A Luxury Experience in the Heart of Athens', max_length=200, verbose_name='Intro Title')),
                ('intro_text', models.TextField(default='Adonis carefully selects the finest locations in Athens to design residential projects that bring you a luxurious lifestyle.', verbose_name='Intro Text')),
            ],
            options={
                'verbose_name': 'Properties Page',
                'verbose_name_plural': 'Properties Page',
            },
        ),
    ]
