# Generated by Django 4.2.28 on 2026-02-22 23:12

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auditlog_chatmessage_customer_chatlead_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Format: G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='microsoft_clarity_id',
            field=models.CharField(blank=True, help_text='Format: xxxxxxxxxx (Project ID from Clarity settings)', max_length=50, verbose_name='Microsoft Clarity ID'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full blog post content with images', verbose_name='Content'),
        ),
    ]
