# Generated by Django 4.2.28 on 2026-02-24 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_sitesettings_google_analytics_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=200, verbose_name='Error Type')),
                ('error_message', models.TextField(verbose_name='Error Message')),
                ('traceback', models.TextField(verbose_name='Full Traceback')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP Method')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Request Data')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='core_errorl_is_read_2a9aa5_idx'), models.Index(fields=['error_type', 'created_at'], name='core_errorl_error_t_d130fa_idx')],
            },
        ),
    ]
