# Generated by Django 4.2.28 on 2026-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenVisaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Subtitle')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_amount', models.CharField(help_text='e.g. €250,000', max_length=50, verbose_name='Price Amount')),
                ('price_label', models.CharField(default='Starting from', help_text='e.g. "Starting from"', max_length=100, verbose_name='Price Label')),
                ('image', models.ImageField(blank=True, help_text='Landscape image recommended (1200x600px minimum)', null=True, upload_to='golden_visa/', verbose_name='Card Background Image')),
                ('detail_page_url', models.SlugField(help_text='URL-friendly slug for the detail page (e.g. "premium-locations")', max_length=200, unique=True, verbose_name='Detail Page URL Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Golden Visa Card',
                'verbose_name_plural': 'Golden Visa Cards',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_golden_is_acti_d3ee78_idx')],
            },
        ),
    ]
