# Generated by Django 4.2.28 on 2026-02-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_golden_visa_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_badge_text',
            field=models.CharField(default='Free Download', help_text='Small badge above the heading, e.g. "Free Download"', max_length=100, verbose_name='Badge Text'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn1_label',
            field=models.CharField(default='View Catalogue', help_text='Small text below the title', max_length=100, verbose_name='Button 1 – Label'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn1_pdf',
            field=models.FileField(blank=True, help_text='Upload the Active Projects catalogue PDF', null=True, upload_to='catalogues/', verbose_name='Button 1 – PDF File'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn1_title',
            field=models.CharField(default='Active Projects', help_text='Bold text on the first download button', max_length=100, verbose_name='Button 1 – Title'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn2_label',
            field=models.CharField(default='Download PDF', help_text='Small text below the title', max_length=100, verbose_name='Button 2 – Label'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn2_pdf',
            field=models.FileField(blank=True, help_text='Upload the Property Price List PDF', null=True, upload_to='catalogues/', verbose_name='Button 2 – PDF File'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn2_title',
            field=models.CharField(default='Property Price List', help_text='Bold text on the second download button', max_length=100, verbose_name='Button 2 – Title'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_heading',
            field=models.CharField(default='Get Our Property Catalogues', max_length=200, verbose_name='Section Heading'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_subtext',
            field=models.CharField(default='Download our comprehensive guides with all available properties and pricing', max_length=300, verbose_name='Sub-text'),
        ),
    ]
