# Generated by Django 4.2.28 on 2026-02-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_frontpage_catalogue_pdfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('slug', models.SlugField(help_text='Auto-generated from title, used in URL', max_length=200, unique=True, verbose_name='URL Slug')),
                ('short_description', models.CharField(help_text='Shown on the event card (max 300 chars)', max_length=300, verbose_name='Short Description')),
                ('full_description', models.TextField(help_text='Shown on the event detail page', verbose_name='Full Description')),
                ('thumbnail', models.ImageField(help_text='Main image shown on the card (recommended: 800x600px)', upload_to='events/thumbnails/', verbose_name='Thumbnail Image')),
                ('video_file', models.FileField(blank=True, help_text='Optional video (MP4 recommended, max 100MB)', null=True, upload_to='events/videos/', verbose_name='Video File')),
                ('video_url', models.URLField(blank=True, help_text='Alternative: paste a YouTube or Vimeo URL', verbose_name='Video URL (YouTube/Vimeo)')),
                ('event_date', models.DateField(blank=True, help_text='Optional date when the event occurred', null=True, verbose_name='Event Date')),
                ('location', models.CharField(blank=True, help_text='Optional location of the event', max_length=200, verbose_name='Location')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this event', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['order', '-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/photos/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this photo', max_length=200, verbose_name='Caption')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the event', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event Photo',
                'verbose_name_plural': 'Event Photos',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'order'], name='core_event_is_acti_552345_idx'),
        ),
    ]
