# Generated by Django 4.2.28 on 2026-02-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('partner_type', models.CharField(choices=[('broker', 'Broker'), ('agent', 'Agent'), ('lawyer', 'Lawyer'), ('client', 'Client'), ('other', 'Other')], max_length=20)),
                ('other_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Title')),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('company', models.CharField(blank=True, max_length=120, null=True, verbose_name='Company / Organization')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message / Notes')),
                ('consent', models.BooleanField(default=False, verbose_name='Consent to be contacted')),
                ('source', models.CharField(default='partnerships', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner Lead',
                'verbose_name_plural': 'Partner Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner_type', 'created_at'], name='core_partne_partner_7454ce_idx'), models.Index(fields=['email'], name='core_partne_email_bec44e_idx')],
            },
        ),
    ]
