# Generated by Django 4.2.28 on 2026-02-27 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_add_partner_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chat_leads', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='conversation_json',
            field=models.JSONField(blank=True, default=list, help_text='Full chat conversation stored as JSON array of {role, text, ts} objects.', verbose_name='Chat Transcript'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='country',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Follow-up Date'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='Internal Notes'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Contacted'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='lead_score',
            field=models.CharField(blank=True, choices=[('hot', '🔥 Hot'), ('warm', '🟡 Warm'), ('cold', '🔵 Cold')], default='warm', max_length=10, verbose_name='Lead Score'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='source_page',
            field=models.CharField(blank=True, max_length=200, verbose_name='Source Page'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow Up'), ('converted', 'Converted'), ('closed', 'Closed')], db_index=True, default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Lead Summary'),
        ),
        migrations.AddIndex(
            model_name='chatlead',
            index=models.Index(fields=['status', 'created_at'], name='core_chatle_status_31cf6e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatlead',
            index=models.Index(fields=['assigned_to', 'status'], name='core_chatle_assigne_c4f490_idx'),
        ),
        migrations.AddIndex(
            model_name='chatlead',
            index=models.Index(fields=['follow_up_date'], name='core_chatle_follow__06080a_idx'),
        ),
    ]
