# Generated by Django 4.2.28 on 2026-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_enhance_chat_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='phone_number_2',
            field=models.CharField(blank=True, help_text='Optional second mobile/WhatsApp number shown in the footer', max_length=20, verbose_name='Second Phone / WhatsApp'),
        ),
    ]
