# Generated by Django 4.2.28 on 2026-02-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_footer_phone_number_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='x_url',
            field=models.URLField(blank=True, help_text='Your X / Twitter profile URL', verbose_name='X (Twitter) URL'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Your YouTube channel URL', verbose_name='YouTube URL'),
        ),
    ]
