# Generated by Django 4.2.28 on 2026-02-28 08:26

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_footer_x_youtube_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full blog post content with images', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_tr',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full blog post content with images', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(help_text='Short summary shown in blog list (max 300 chars)', max_length=300, null=True, verbose_name='Excerpt / Summary'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_tr',
            field=models.TextField(help_text='Short summary shown in blog list (max 300 chars)', max_length=300, null=True, verbose_name='Excerpt / Summary'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='Description for search engines (max 160 chars). Leave blank to use excerpt.', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_tr',
            field=models.CharField(blank=True, help_text='Description for search engines (max 160 chars). Leave blank to use excerpt.', max_length=160, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='Title for search engines (max 70 chars). Leave blank to use post title.', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_tr',
            field=models.CharField(blank=True, help_text='Title for search engines (max 70 chars). Leave blank to use post title.', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description_en',
            field=models.CharField(blank=True, help_text='Description for social media sharing', max_length=200, null=True, verbose_name='Social Description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description_tr',
            field=models.CharField(blank=True, help_text='Description for social media sharing', max_length=200, null=True, verbose_name='Social Description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title_en',
            field=models.CharField(blank=True, help_text='Title for social media sharing', max_length=100, null=True, verbose_name='Social Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title_tr',
            field=models.CharField(blank=True, help_text='Title for social media sharing', max_length=100, null=True, verbose_name='Social Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_en',
            field=models.SlugField(help_text='URL-friendly version of title (auto-generated)', null=True, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_tr',
            field=models.SlugField(help_text='URL-friendly version of title (auto-generated)', null=True, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='full_description_en',
            field=models.TextField(help_text='Shown on the event detail page', null=True, verbose_name='Full Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='full_description_tr',
            field=models.TextField(help_text='Shown on the event detail page', null=True, verbose_name='Full Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_en',
            field=models.CharField(help_text='Shown on the event card (max 300 chars)', max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='short_description_tr',
            field=models.CharField(help_text='Shown on the event card (max 300 chars)', max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug_en',
            field=models.SlugField(help_text='Auto-generated from title, used in URL', max_length=200, null=True, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug_tr',
            field=models.SlugField(help_text='Auto-generated from title, used in URL', max_length=200, null=True, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tr',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='subtitle_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='subtitle_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_tr',
            field=models.TextField(null=True),
        ),
    ]
