# Generated by Django 4.2.28 on 2026-02-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_blogcategory_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='description_en',
            field=models.TextField(default='Your trusted partner for Greek residency and smart investment. Built on experience, driven by trust, focused on your future in Europe.', null=True, verbose_name='Footer Description'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='description_tr',
            field=models.TextField(default='Your trusted partner for Greek residency and smart investment. Built on experience, driven by trust, focused on your future in Europe.', null=True, verbose_name='Footer Description'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='whatsapp_button_text_en',
            field=models.CharField(default='Chat Now', max_length=50, null=True, verbose_name='WhatsApp Button Text'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='whatsapp_button_text_tr',
            field=models.CharField(default='Chat Now', max_length=50, null=True, verbose_name='WhatsApp Button Text'),
        ),
    ]
