# Generated by Django 4.2.28 on 2026-02-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_translate_footer_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershippagesettings',
            name='b2b_text_en',
            field=models.TextField(default='Adonis Group offers a unique opportunity for real estate professionals...', help_text='Main text explaining why businesses should partner with Adonis', null=True, verbose_name='B2B Description'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='b2b_text_tr',
            field=models.TextField(default='Adonis Group offers a unique opportunity for real estate professionals...', help_text='Main text explaining why businesses should partner with Adonis', null=True, verbose_name='B2B Description'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='b2b_title_en',
            field=models.CharField(default='Why B2B With Adonis Group?', max_length=200, null=True, verbose_name='B2B Section Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='b2b_title_tr',
            field=models.CharField(default='Why B2B With Adonis Group?', max_length=200, null=True, verbose_name='B2B Section Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_1_text_en',
            field=models.TextField(default='Earn attractive commissions on every successful referral and sale.', null=True, verbose_name='Benefit 1 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_1_text_tr',
            field=models.TextField(default='Earn attractive commissions on every successful referral and sale.', null=True, verbose_name='Benefit 1 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_1_title_en',
            field=models.CharField(default='Competitive Commission', max_length=100, null=True, verbose_name='Benefit 1 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_1_title_tr',
            field=models.CharField(default='Competitive Commission', max_length=100, null=True, verbose_name='Benefit 1 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_2_text_en',
            field=models.TextField(default='Access to premium properties not available on the open market.', null=True, verbose_name='Benefit 2 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_2_text_tr',
            field=models.TextField(default='Access to premium properties not available on the open market.', null=True, verbose_name='Benefit 2 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_2_title_en',
            field=models.CharField(default='Exclusive Inventory', max_length=100, null=True, verbose_name='Benefit 2 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_2_title_tr',
            field=models.CharField(default='Exclusive Inventory', max_length=100, null=True, verbose_name='Benefit 2 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_3_text_en',
            field=models.TextField(default='Full support from our team throughout the entire sales process.', null=True, verbose_name='Benefit 3 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_3_text_tr',
            field=models.TextField(default='Full support from our team throughout the entire sales process.', null=True, verbose_name='Benefit 3 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_3_title_en',
            field=models.CharField(default='Dedicated Support', max_length=100, null=True, verbose_name='Benefit 3 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_3_title_tr',
            field=models.CharField(default='Dedicated Support', max_length=100, null=True, verbose_name='Benefit 3 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_4_text_en',
            field=models.TextField(default='Comprehensive training materials and marketing resources.', null=True, verbose_name='Benefit 4 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_4_text_tr',
            field=models.TextField(default='Comprehensive training materials and marketing resources.', null=True, verbose_name='Benefit 4 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_4_title_en',
            field=models.CharField(default='Training & Resources', max_length=100, null=True, verbose_name='Benefit 4 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_4_title_tr',
            field=models.CharField(default='Training & Resources', max_length=100, null=True, verbose_name='Benefit 4 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_5_text_en',
            field=models.TextField(default='Join our international network of real estate professionals.', null=True, verbose_name='Benefit 5 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_5_text_tr',
            field=models.TextField(default='Join our international network of real estate professionals.', null=True, verbose_name='Benefit 5 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_5_title_en',
            field=models.CharField(default='Global Network', max_length=100, null=True, verbose_name='Benefit 5 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_5_title_tr',
            field=models.CharField(default='Global Network', max_length=100, null=True, verbose_name='Benefit 5 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_6_text_en',
            field=models.TextField(default='Expand your business with the growing Golden Visa market.', null=True, verbose_name='Benefit 6 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_6_text_tr',
            field=models.TextField(default='Expand your business with the growing Golden Visa market.', null=True, verbose_name='Benefit 6 Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_6_title_en',
            field=models.CharField(default='Growth Opportunity', max_length=100, null=True, verbose_name='Benefit 6 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='benefit_6_title_tr',
            field=models.CharField(default='Growth Opportunity', max_length=100, null=True, verbose_name='Benefit 6 Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='cta_button_text_en',
            field=models.CharField(default='Become a Partner', max_length=50, null=True, verbose_name='CTA Button Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='cta_button_text_tr',
            field=models.CharField(default='Become a Partner', max_length=50, null=True, verbose_name='CTA Button Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='cta_text_en',
            field=models.TextField(default='Contact us today to learn more about our partnership program and start earning.', null=True, verbose_name='CTA Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='cta_text_tr',
            field=models.TextField(default='Contact us today to learn more about our partnership program and start earning.', null=True, verbose_name='CTA Text'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='cta_title_en',
            field=models.CharField(default='Ready to Become a Partner?', max_length=200, null=True, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='cta_title_tr',
            field=models.CharField(default='Ready to Become a Partner?', max_length=200, null=True, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='hero_subtitle_en',
            field=models.TextField(default='Join our exclusive network of real estate professionals and unlock new opportunities in the Greek Golden Visa market.', null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='hero_subtitle_tr',
            field=models.TextField(default='Join our exclusive network of real estate professionals and unlock new opportunities in the Greek Golden Visa market.', null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='hero_title_en',
            field=models.CharField(default='Partner With Adonis Group', max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='hero_title_tr',
            field=models.CharField(default='Partner With Adonis Group', max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='video_subtitle_en',
            field=models.TextField(blank=True, default='Watch how our partners grow their business with Adonis Group.', null=True, verbose_name='Video Section Subtitle'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='video_subtitle_tr',
            field=models.TextField(blank=True, default='Watch how our partners grow their business with Adonis Group.', null=True, verbose_name='Video Section Subtitle'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='video_title_en',
            field=models.CharField(blank=True, default='Discover Our Partnership Program', max_length=200, null=True, verbose_name='Video Section Title'),
        ),
        migrations.AddField(
            model_name='partnershippagesettings',
            name='video_title_tr',
            field=models.CharField(blank=True, default='Discover Our Partnership Program', max_length=200, null=True, verbose_name='Video Section Title'),
        ),
    ]
