# Generated by Django 4.2.28 on 2026-02-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_translate_partnership_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_badge_text_en',
            field=models.CharField(default='Free Download', help_text='Small badge above the heading, e.g. "Free Download"', max_length=100, null=True, verbose_name='Badge Text'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_badge_text_tr',
            field=models.CharField(default='Free Download', help_text='Small badge above the heading, e.g. "Free Download"', max_length=100, null=True, verbose_name='Badge Text'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn1_label_en',
            field=models.CharField(default='View Catalogue', help_text='Small text below the title', max_length=100, null=True, verbose_name='Button 1 – Label'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn1_label_tr',
            field=models.CharField(default='View Catalogue', help_text='Small text below the title', max_length=100, null=True, verbose_name='Button 1 – Label'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn1_title_en',
            field=models.CharField(default='Active Projects', help_text='Bold text on the first download button', max_length=100, null=True, verbose_name='Button 1 – Title'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn1_title_tr',
            field=models.CharField(default='Active Projects', help_text='Bold text on the first download button', max_length=100, null=True, verbose_name='Button 1 – Title'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn2_label_en',
            field=models.CharField(default='Download PDF', help_text='Small text below the title', max_length=100, null=True, verbose_name='Button 2 – Label'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn2_label_tr',
            field=models.CharField(default='Download PDF', help_text='Small text below the title', max_length=100, null=True, verbose_name='Button 2 – Label'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn2_title_en',
            field=models.CharField(default='Property Price List', help_text='Bold text on the second download button', max_length=100, null=True, verbose_name='Button 2 – Title'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_btn2_title_tr',
            field=models.CharField(default='Property Price List', help_text='Bold text on the second download button', max_length=100, null=True, verbose_name='Button 2 – Title'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_heading_en',
            field=models.CharField(default='Get Our Property Catalogues', max_length=200, null=True, verbose_name='Section Heading'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_heading_tr',
            field=models.CharField(default='Get Our Property Catalogues', max_length=200, null=True, verbose_name='Section Heading'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_subtext_en',
            field=models.CharField(default='Download our comprehensive guides with all available properties and pricing', max_length=300, null=True, verbose_name='Sub-text'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='catalogue_subtext_tr',
            field=models.CharField(default='Download our comprehensive guides with all available properties and pricing', max_length=300, null=True, verbose_name='Sub-text'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='contact_badge_en',
            field=models.CharField(default='Get In Touch', max_length=100, null=True, verbose_name='Contact Badge'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='contact_badge_tr',
            field=models.CharField(default='Get In Touch', max_length=100, null=True, verbose_name='Contact Badge'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='contact_description_en',
            field=models.TextField(default='Fill out the form and our expert advisors will guide you through the process step by step, with clear answers to all your questions.', null=True, verbose_name='Contact Description'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='contact_description_tr',
            field=models.TextField(default='Fill out the form and our expert advisors will guide you through the process step by step, with clear answers to all your questions.', null=True, verbose_name='Contact Description'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='contact_title_en',
            field=models.CharField(default='Book a Free Consultation', max_length=200, null=True, verbose_name='Contact Title'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='contact_title_tr',
            field=models.CharField(default='Book a Free Consultation', max_length=200, null=True, verbose_name='Contact Title'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='process_badge_en',
            field=models.CharField(default='How It Works', max_length=100, null=True, verbose_name='Process Badge Text'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='process_badge_tr',
            field=models.CharField(default='How It Works', max_length=100, null=True, verbose_name='Process Badge Text'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='process_description_en',
            field=models.TextField(default='Fast, Guaranteed & Recommended - Our streamlined process ensures your success', null=True, verbose_name='Process Description'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='process_description_tr',
            field=models.TextField(default='Fast, Guaranteed & Recommended - Our streamlined process ensures your success', null=True, verbose_name='Process Description'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='process_title_en',
            field=models.CharField(default='Residency Process in Greece', max_length=200, null=True, verbose_name='Process Title'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='process_title_tr',
            field=models.CharField(default='Residency Process in Greece', max_length=200, null=True, verbose_name='Process Title'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='services_badge_en',
            field=models.CharField(default='Why Choose Us', max_length=100, null=True, verbose_name='Services Badge Text'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='services_badge_tr',
            field=models.CharField(default='Why Choose Us', max_length=100, null=True, verbose_name='Services Badge Text'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='services_description_en',
            field=models.TextField(default='With a minimum investment of €250,000 in Greek real estate, you can obtain permanent residency in Europe and, over time, a high-ranking Greek passport.', null=True, verbose_name='Services Description'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='services_description_tr',
            field=models.TextField(default='With a minimum investment of €250,000 in Greek real estate, you can obtain permanent residency in Europe and, over time, a high-ranking Greek passport.', null=True, verbose_name='Services Description'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='services_title_en',
            field=models.CharField(default='Golden Visa & Greek Passport', max_length=200, null=True, verbose_name='Services Title'),
        ),
        migrations.AddField(
            model_name='frontpagesettings',
            name='services_title_tr',
            field=models.CharField(default='Golden Visa & Greek Passport', max_length=200, null=True, verbose_name='Services Title'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='contact_button_text_en',
            field=models.CharField(default='Contact Us', help_text='Text shown on the green WhatsApp button in header', max_length=50, null=True, verbose_name='Contact Button Text'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='contact_button_text_tr',
            field=models.CharField(default='Contact Us', help_text='Text shown on the green WhatsApp button in header', max_length=50, null=True, verbose_name='Contact Button Text'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='hero_subtitle_en',
            field=models.TextField(default='Permanent residency for your family by purchasing property in Greece | Official offices in Athens', help_text='Sub-heading text below the title', null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='hero_subtitle_tr',
            field=models.TextField(default='Permanent residency for your family by purchasing property in Greece | Official offices in Athens', help_text='Sub-heading text below the title', null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='hero_title_en',
            field=models.CharField(default='Greek Residency', help_text='Main heading text in hero section', max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='hero_title_tr',
            field=models.CharField(default='Greek Residency', help_text='Main heading text in hero section', max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='intro_text_en',
            field=models.TextField(default='At Adonis Group, we specialize in helping international investors and families secure their Greek Golden Visa through strategic real estate investments. With offices in Athens and Tehran, our multilingual team provides end-to-end support—from property selection to residency approval.', help_text='Description text next to the intro video', null=True, verbose_name='Intro Text'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='intro_text_tr',
            field=models.TextField(default='At Adonis Group, we specialize in helping international investors and families secure their Greek Golden Visa through strategic real estate investments. With offices in Athens and Tehran, our multilingual team provides end-to-end support—from property selection to residency approval.', help_text='Description text next to the intro video', null=True, verbose_name='Intro Text'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='intro_title_en',
            field=models.CharField(default='Welcome to Adonis Group', help_text='Title displayed next to the intro video', max_length=200, null=True, verbose_name='Intro Title'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='intro_title_tr',
            field=models.CharField(default='Welcome to Adonis Group', help_text='Title displayed next to the intro video', max_length=200, null=True, verbose_name='Intro Title'),
        ),
    ]
