# Generated by Django 4.2.28 on 2026-03-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_translate_header_frontpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershippagesettings',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube or Vimeo URL (e.g. https://www.youtube.com/watch?v=...). Used when no file is uploaded.', max_length=500, verbose_name='Partnership Video (URL)'),
        ),
        migrations.AlterField(
            model_name='partnershippagesettings',
            name='video',
            field=models.FileField(blank=True, help_text='Upload an MP4 file. Leave blank if you prefer to use a Video URL instead.', null=True, upload_to='partnership/', verbose_name='Partnership Video (File)'),
        ),
        migrations.AlterField(
            model_name='partnershippagesettings',
            name='video_cover',
            field=models.ImageField(blank=True, help_text='Cover image shown before the video plays (used as poster for file videos and as thumbnail for URL videos).', null=True, upload_to='partnership/', verbose_name='Video Cover / Thumbnail'),
        ),
    ]
