# Generated by Django 4.2.28 on 2026-03-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_partnership_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube URL (e.g. https://www.youtube.com/watch?v=...). Used as background when no file is uploaded.', max_length=500, verbose_name='Hero Video (YouTube URL)'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Upload an MP4 background video. Leave blank if you prefer to use a YouTube URL instead.', null=True, upload_to='hero/', verbose_name='Hero Video (File)'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='hero_video_poster',
            field=models.ImageField(blank=True, help_text='Shown while video loads, on mobile, or when no video is set.', null=True, upload_to='hero/', verbose_name='Video Poster / Fallback Image'),
        ),
    ]
