# Generated by Django 4.2.28 on 2026-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_headersettings_hero_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='intro_video_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube URL (e.g. https://www.youtube.com/watch?v=...). Used when no file is uploaded.', max_length=500, verbose_name='Intro Video (YouTube URL)'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='intro_video',
            field=models.FileField(blank=True, help_text='Upload an MP4 video. Leave blank if you prefer to use a YouTube URL instead.', null=True, upload_to='intro/', verbose_name='Intro Video (File)'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='intro_video_poster',
            field=models.ImageField(blank=True, help_text='Cover image shown before the video plays. Highly recommended when using a YouTube URL.', null=True, upload_to='intro/', verbose_name='Intro Video Cover Photo'),
        ),
    ]
