# Generated by Django 4.2.28 on 2026-03-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_golden_visa_landing_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenvisalandingpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
