# Generated by Django 4.2.28 on 2026-03-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_goldenvisalandingpage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Full-width background photo for the hero section (recommended: 1920×1080 px).', null=True, upload_to='golden_visa_landing/', verbose_name='Hero Background Image'),
        ),
    ]
