# Generated by Django 4.2.28 on 2026-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_golden_visa_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('home', 'Home Page'), ('properties', 'Properties Listing'), ('golden_visa', 'Greek Golden Visa'), ('blog', 'Blog'), ('contact', 'Contact'), ('about', 'About'), ('partnerships', 'Partnerships')], max_length=50, unique=True, verbose_name='Page')),
                ('meta_title_en', models.CharField(blank=True, help_text='Max 70 chars. Shown in Google search results.', max_length=70, verbose_name='Meta Title (EN)')),
                ('meta_desc_en', models.CharField(blank=True, help_text='Max 160 chars. Shown as the snippet in Google.', max_length=160, verbose_name='Meta Description (EN)')),
                ('og_title_en', models.CharField(blank=True, help_text='Social share title. Leave blank to inherit Meta Title.', max_length=100, verbose_name='OG Title (EN)')),
                ('og_desc_en', models.CharField(blank=True, help_text='Social share description. Leave blank to inherit Meta Description.', max_length=200, verbose_name='OG Description (EN)')),
                ('meta_title_tr', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (TR)')),
                ('meta_desc_tr', models.CharField(blank=True, max_length=160, verbose_name='Meta Description (TR)')),
                ('og_title_tr', models.CharField(blank=True, max_length=100, verbose_name='OG Title (TR)')),
                ('og_desc_tr', models.CharField(blank=True, max_length=200, verbose_name='OG Description (TR)')),
                ('og_image', models.ImageField(blank=True, help_text='Recommended 1200×630 px. Used for all languages.', null=True, upload_to='seo/og/', verbose_name='OG / Share Image')),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
                'ordering': ['page_key'],
            },
        ),
    ]
