# Generated by Django 4.2.28 on 2026-03-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_page_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword this post targets (e.g. "greece golden visa 250k"). Used for SEO analysis.', max_length=120, verbose_name='Focus Keyword'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Custom social sharing image (recommended 1200×630 px). Leave blank to use featured image.', null=True, upload_to='seo/og/', verbose_name='OG Image'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Leave blank — canonical is set automatically to /greekgoldenvisa/.', verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword for this landing page (e.g. "greek golden visa programme"). Used for SEO analysis.', max_length=120, verbose_name='Focus Keyword'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Leave blank — canonical is set automatically from the page URL', verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Description for search engines (max 160 chars). Leave blank to use excerpt.', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='Description for search engines (max 160 chars). Leave blank to use excerpt.', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description_tr',
            field=models.CharField(blank=True, help_text='Description for search engines (max 160 chars). Leave blank to use excerpt.', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated secondary keywords', max_length=200, verbose_name='SEO Keywords'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_description',
            field=models.CharField(blank=True, help_text='Description for social sharing. Leave blank to use Meta Description.', max_length=200, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_description_en',
            field=models.CharField(blank=True, help_text='Description for social sharing. Leave blank to use Meta Description.', max_length=200, null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_description_tr',
            field=models.CharField(blank=True, help_text='Description for social sharing. Leave blank to use Meta Description.', max_length=200, null=True, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for social sharing. Leave blank to use SEO Title.', max_length=100, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_title_en',
            field=models.CharField(blank=True, help_text='Title for social sharing. Leave blank to use SEO Title.', max_length=100, null=True, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_title_tr',
            field=models.CharField(blank=True, help_text='Title for social sharing. Leave blank to use SEO Title.', max_length=100, null=True, verbose_name='OG Title'),
        ),
    ]
