# Generated by Django 4.2.28 on 2026-03-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_seo_fields_blogpost_goldenvisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='robots_follow',
            field=models.BooleanField(default=True, verbose_name='Follow links'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Uncheck to add noindex.', verbose_name='Allow indexing'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_allow_publish_override',
            field=models.BooleanField(default=False, verbose_name='Override SEO check'),
        ),
        migrations.AddField(
            model_name='event',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=120, verbose_name='Focus Keyword'),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Max 160 chars. Leave blank to use short description.', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='OG Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='robots_follow',
            field=models.BooleanField(default=True, verbose_name='Follow links'),
        ),
        migrations.AddField(
            model_name='event',
            name='robots_index',
            field=models.BooleanField(default=True, verbose_name='Allow indexing'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_allow_publish_override',
            field=models.BooleanField(default=False, verbose_name='Override SEO check'),
        ),
        migrations.AddField(
            model_name='event',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Max 70 chars. Leave blank to use event title.', max_length=70, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail_alt',
            field=models.CharField(blank=True, help_text='Alt text for the thumbnail (required for SEO).', max_length=200, verbose_name='Thumbnail ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=120, verbose_name='Focus Keyword'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the card background image.', max_length=200, verbose_name='Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='OG Image'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='robots_follow',
            field=models.BooleanField(default=True, verbose_name='Follow links'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='robots_index',
            field=models.BooleanField(default=True, verbose_name='Allow indexing'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='seo_allow_publish_override',
            field=models.BooleanField(default=False, verbose_name='Override SEO check'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='robots_follow',
            field=models.BooleanField(default=True, verbose_name='Follow links'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='robots_index',
            field=models.BooleanField(default=True, verbose_name='Allow indexing'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Image ALT Text'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='robots_follow',
            field=models.BooleanField(default=True, verbose_name='Follow links'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='robots_index',
            field=models.BooleanField(default=True, verbose_name='Allow indexing'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='seo_allow_publish_override',
            field=models.BooleanField(default=False, verbose_name='Override SEO check'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='SEO Title'),
        ),
    ]
