# Generated by Django 4.2.28 on 2026-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_seo_fields_event_gvcard_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Optional. Upload an MP4 video for the hero section. Falls back to hero image if not set.', null=True, upload_to='golden_visa_landing/', verbose_name='Hero Background Video (MP4)'),
        ),
        migrations.AlterField(
            model_name='goldenvisalandingpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Leave blank — canonical is set automatically to /greece-golden-visa/.', verbose_name='Canonical URL'),
        ),
    ]
