# Generated by Django 4.2.28 on 2026-03-05 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_hero_video_to_gv_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='hero_video_opacity',
            field=models.PositiveIntegerField(default=100, help_text='Controls video visibility: 100 = fully visible, 60 = darker video.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Hero Video Opacity (%)'),
        ),
    ]
