# Generated by Django 4.2.28 on 2026-03-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_goldenvisalandingpage_hero_video_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='hero_image_alt',
            field=models.CharField(blank=True, help_text='Describe the hero image for screen readers and Google Image Search.', max_length=200, verbose_name='Hero Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='og_description',
            field=models.CharField(blank=True, help_text='Social share description. Leave blank to use meta description.', max_length=200, verbose_name='OG Description'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Social share title for Facebook, LinkedIn, WhatsApp. Leave blank to use SEO title.', max_length=100, verbose_name='OG Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='seo_allow_publish_override',
            field=models.BooleanField(default=False, help_text='Superadmin only — allows publishing even with critical SEO issues.', verbose_name='Override SEO check'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_250_image_alt',
            field=models.CharField(blank=True, help_text='ALT text for the €250K tier image.', max_length=200, verbose_name='€250K Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_400_image_alt',
            field=models.CharField(blank=True, help_text='ALT text for the €400K tier image.', max_length=200, verbose_name='€400K Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_800_image_alt',
            field=models.CharField(blank=True, help_text='ALT text for the €800K tier image.', max_length=200, verbose_name='€800K Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description. Leave blank to use meta description.', max_length=200, verbose_name='Twitter Description'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter card image (recommended: 1200×628 px). Leave blank to use OG image.', null=True, upload_to='golden_visa_landing/', verbose_name='Twitter Card Image'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title. Leave blank to use OG/SEO title.', max_length=100, verbose_name='Twitter Title'),
        ),
    ]
