# Generated by Django 4.2.28 on 2026-03-07 13:14

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_gv_landing_seo_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenvisalandingpage',
            name='intro_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text shown below the hero. Use H2/H3 headings, bold, lists and links to structure the content.', verbose_name='Intro / About Text'),
        ),
    ]
