# Generated by Django 4.2.28 on 2026-03-07 14:09

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_gv_landing_intro_ckeditor5'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_1_image',
            field=models.ImageField(blank=True, help_text='Optional image shown to the right of the section 1 text (min 800×600 px recommended).', null=True, upload_to='golden_visa_landing/sections/', verbose_name='Section 1 — Image'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_1_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Section 1 — Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_1_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text content for section 1. Supports bold, lists, links, headings.', verbose_name='Section 1 — Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_1_title',
            field=models.CharField(blank=True, help_text='Heading for the first content section (text on left, image on right).', max_length=200, verbose_name='Section 1 — Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_2_image',
            field=models.ImageField(blank=True, help_text='Optional image shown to the left of the section 2 text.', null=True, upload_to='golden_visa_landing/sections/', verbose_name='Section 2 — Image'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_2_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Section 2 — Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_2_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Section 2 — Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_2_title',
            field=models.CharField(blank=True, help_text='Heading for the second content section (image on left, text on right).', max_length=200, verbose_name='Section 2 — Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_3_image',
            field=models.ImageField(blank=True, help_text='Optional image shown to the right of the section 3 text.', null=True, upload_to='golden_visa_landing/sections/', verbose_name='Section 3 — Image'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_3_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Section 3 — Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_3_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Section 3 — Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_3_title',
            field=models.CharField(blank=True, help_text='Heading for the third content section (text on left, image on right).', max_length=200, verbose_name='Section 3 — Title'),
        ),
        migrations.AlterField(
            model_name='goldenvisalandingpage',
            name='intro_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Short introductory paragraph shown directly below the hero (centered, full-width). Keep this brief — use the Content Sections below for detailed zig-zag layout blocks.', verbose_name='Intro / About Text'),
        ),
    ]
