# Generated by Django 4.2.28 on 2026-03-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_gv_landing_content_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='benefits_bg_image',
            field=models.ImageField(blank=True, help_text='Full-width background photo for the "Why Choose Us" section. Use a high-quality landscape image (min 1920×800 px recommended).', null=True, upload_to='golden_visa_landing/', verbose_name='Benefits Section — Background Image'),
        ),
    ]
