# Generated by Django 4.2.28 on 2026-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_hybrid_chat_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlead',
            name='language',
            field=models.CharField(blank=True, help_text='Detected language code, e.g. EN, FA, EL.', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='source',
            field=models.CharField(choices=[('chat_widget', 'Chat Widget'), ('contact_form', 'Contact Form'), ('phone', 'Phone'), ('email', 'Email'), ('referral', 'Referral'), ('other', 'Other')], db_index=True, default='chat_widget', max_length=30, verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='telegram_sent',
            field=models.BooleanField(default=False, verbose_name='Telegram Sent'),
        ),
        migrations.AddField(
            model_name='chatlead',
            name='telegram_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Telegram Sent At'),
        ),
    ]
