# Generated by Django 4.2.28 on 2026-03-09 10:08

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_chatlead_telegram_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='benefits_text_en',
            field=models.TextField(blank=True, default='EU Permanent Residency\nVisa-Free Travel in Schengen Zone\nIncludes Spouse & Dependent Children\nNo Minimum Stay Requirement\nPath to Greek Citizenship after 7 Years\nStrong ROI on Greek Real Estate\nAccess to EU Healthcare & Education\nFast Processing — Typically 2–3 Months', help_text='Enter each benefit on its own line. They will be displayed as a grid of cards.', null=True, verbose_name='Benefits (one per line)'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='benefits_text_tr',
            field=models.TextField(blank=True, default='EU Permanent Residency\nVisa-Free Travel in Schengen Zone\nIncludes Spouse & Dependent Children\nNo Minimum Stay Requirement\nPath to Greek Citizenship after 7 Years\nStrong ROI on Greek Real Estate\nAccess to EU Healthcare & Education\nFast Processing — Typically 2–3 Months', help_text='Enter each benefit on its own line. They will be displayed as a grid of cards.', null=True, verbose_name='Benefits (one per line)'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='benefits_title_en',
            field=models.CharField(default='Why Choose the Greek Golden Visa?', max_length=200, null=True, verbose_name='Benefits Section Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='benefits_title_tr',
            field=models.CharField(default='Why Choose the Greek Golden Visa?', max_length=200, null=True, verbose_name='Benefits Section Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='hero_subtitle_en',
            field=models.TextField(default='Secure EU permanent residency for your family through strategic property investment in Greece.', null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='hero_subtitle_tr',
            field=models.TextField(default='Secure EU permanent residency for your family through strategic property investment in Greece.', null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='hero_title_en',
            field=models.CharField(default='Greek Golden Visa', max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='hero_title_tr',
            field=models.CharField(default='Greek Golden Visa', max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='intro_text_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Short introductory paragraph shown directly below the hero (centered, full-width). Keep this brief — use the Content Sections below for detailed zig-zag layout blocks.', null=True, verbose_name='Intro / About Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='intro_text_tr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Short introductory paragraph shown directly below the hero (centered, full-width). Keep this brief — use the Content Sections below for detailed zig-zag layout blocks.', null=True, verbose_name='Intro / About Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='process_steps_en',
            field=models.TextField(blank=True, default='Choose Your Investment Tier\nSelect a Qualifying Property with Adonis\nComplete Legal Due Diligence\nSign Purchase Agreement & Transfer Funds\nSubmit Golden Visa Application\nReceive Residency Permit (5-Year Renewable)', help_text='Each line becomes a numbered step card.', null=True, verbose_name='Process Steps (one per line)'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='process_steps_tr',
            field=models.TextField(blank=True, default='Choose Your Investment Tier\nSelect a Qualifying Property with Adonis\nComplete Legal Due Diligence\nSign Purchase Agreement & Transfer Funds\nSubmit Golden Visa Application\nReceive Residency Permit (5-Year Renewable)', help_text='Each line becomes a numbered step card.', null=True, verbose_name='Process Steps (one per line)'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='process_title_en',
            field=models.CharField(default='How It Works', max_length=200, null=True, verbose_name='Process Section Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='process_title_tr',
            field=models.CharField(default='How It Works', max_length=200, null=True, verbose_name='Process Section Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_1_text_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text content for section 1. Supports bold, lists, links, headings.', null=True, verbose_name='Section 1 — Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_1_text_tr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text content for section 1. Supports bold, lists, links, headings.', null=True, verbose_name='Section 1 — Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_1_title_en',
            field=models.CharField(blank=True, help_text='Heading for the first content section (text on left, image on right).', max_length=200, null=True, verbose_name='Section 1 — Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_1_title_tr',
            field=models.CharField(blank=True, help_text='Heading for the first content section (text on left, image on right).', max_length=200, null=True, verbose_name='Section 1 — Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_2_text_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Section 2 — Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_2_text_tr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Section 2 — Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_2_title_en',
            field=models.CharField(blank=True, help_text='Heading for the second content section (image on left, text on right).', max_length=200, null=True, verbose_name='Section 2 — Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_2_title_tr',
            field=models.CharField(blank=True, help_text='Heading for the second content section (image on left, text on right).', max_length=200, null=True, verbose_name='Section 2 — Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_3_text_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Section 3 — Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_3_text_tr',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Section 3 — Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_3_title_en',
            field=models.CharField(blank=True, help_text='Heading for the third content section (text on left, image on right).', max_length=200, null=True, verbose_name='Section 3 — Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_3_title_tr',
            field=models.CharField(blank=True, help_text='Heading for the third content section (text on left, image on right).', max_length=200, null=True, verbose_name='Section 3 — Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_250_desc_en',
            field=models.TextField(default='Invest in converted commercial-to-residential properties across Greece starting from €250,000.', null=True, verbose_name='€250K Tier Description'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_250_desc_tr',
            field=models.TextField(default='Invest in converted commercial-to-residential properties across Greece starting from €250,000.', null=True, verbose_name='€250K Tier Description'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_250_title_en',
            field=models.CharField(default='Commercial-to-Residential Converted Properties', max_length=200, null=True, verbose_name='€250K Tier Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_250_title_tr',
            field=models.CharField(default='Commercial-to-Residential Converted Properties', max_length=200, null=True, verbose_name='€250K Tier Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_400_desc_en',
            field=models.TextField(default='Invest in properties across other Greek regions starting from €400,000.', null=True, verbose_name='€400K Tier Description'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_400_desc_tr',
            field=models.TextField(default='Invest in properties across other Greek regions starting from €400,000.', null=True, verbose_name='€400K Tier Description'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_400_title_en',
            field=models.CharField(default='Other Greek Regions', max_length=200, null=True, verbose_name='€400K Tier Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_400_title_tr',
            field=models.CharField(default='Other Greek Regions', max_length=200, null=True, verbose_name='€400K Tier Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_800_desc_en',
            field=models.TextField(default='Invest in premium locations such as Athens, Thessaloniki, Mykonos, and Santorini starting from €800,000.', null=True, verbose_name='€800K Tier Description'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_800_desc_tr',
            field=models.TextField(default='Invest in premium locations such as Athens, Thessaloniki, Mykonos, and Santorini starting from €800,000.', null=True, verbose_name='€800K Tier Description'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_800_title_en',
            field=models.CharField(default='Premium Locations', max_length=200, null=True, verbose_name='€800K Tier Title'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_800_title_tr',
            field=models.CharField(default='Premium Locations', max_length=200, null=True, verbose_name='€800K Tier Title'),
        ),
    ]
