# Generated by Django 4.2.28 on 2026-03-09 15:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_gv_landing_copy_en_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagesettings',
            name='about_text_en',
            field=ckeditor.fields.RichTextField(default='<p>At Adonis Group, we carefully select the finest locations in Athens to create residential projects that combine modern design, comfort, and investment security.</p>', help_text='Main about us text. You can use formatting here.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='about_text_tr',
            field=ckeditor.fields.RichTextField(default='<p>At Adonis Group, we carefully select the finest locations in Athens to create residential projects that combine modern design, comfort, and investment security.</p>', help_text='Main about us text. You can use formatting here.', null=True, verbose_name='About Text'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='about_title_en',
            field=models.CharField(default='Who We Are', max_length=200, null=True, verbose_name='About Section Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='about_title_tr',
            field=models.CharField(default='Who We Are', max_length=200, null=True, verbose_name='About Section Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='hero_subtitle_en',
            field=models.TextField(default='Built on experience, driven by trust, focused on your future in Europe', null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='hero_subtitle_tr',
            field=models.TextField(default='Built on experience, driven by trust, focused on your future in Europe', null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='hero_title_en',
            field=models.CharField(default='Your Trusted Partner for Greek Residency', max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='hero_title_tr',
            field=models.CharField(default='Your Trusted Partner for Greek Residency', max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='team_subtitle_en',
            field=models.TextField(blank=True, default='Meet the professionals behind Adonis Group', null=True, verbose_name='Team Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='team_subtitle_tr',
            field=models.TextField(blank=True, default='Meet the professionals behind Adonis Group', null=True, verbose_name='Team Subtitle'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='team_title_en',
            field=models.CharField(default='Our Team', max_length=100, null=True, verbose_name='Team Section Title'),
        ),
        migrations.AddField(
            model_name='aboutpagesettings',
            name='team_title_tr',
            field=models.CharField(default='Our Team', max_length=100, null=True, verbose_name='Team Section Title'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_alt_en',
            field=models.CharField(blank=True, help_text='Alternative text for SEO and accessibility', max_length=200, null=True, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_alt_tr',
            field=models.CharField(blank=True, help_text='Alternative text for SEO and accessibility', max_length=200, null=True, verbose_name='Image Alt Text'),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail_alt_en',
            field=models.CharField(blank=True, help_text='Alt text for the thumbnail (required for SEO).', max_length=200, null=True, verbose_name='Thumbnail ALT Text'),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail_alt_tr',
            field=models.CharField(blank=True, help_text='Alt text for the thumbnail (required for SEO).', max_length=200, null=True, verbose_name='Thumbnail ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='image_alt_en',
            field=models.CharField(blank=True, help_text='Alt text for the card background image.', max_length=200, null=True, verbose_name='Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisacard',
            name='image_alt_tr',
            field=models.CharField(blank=True, help_text='Alt text for the card background image.', max_length=200, null=True, verbose_name='Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='hero_image_alt_en',
            field=models.CharField(blank=True, help_text='Describe the hero image for screen readers and Google Image Search.', max_length=200, null=True, verbose_name='Hero Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='hero_image_alt_tr',
            field=models.CharField(blank=True, help_text='Describe the hero image for screen readers and Google Image Search.', max_length=200, null=True, verbose_name='Hero Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_1_image_alt_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Section 1 — Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_1_image_alt_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Section 1 — Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_2_image_alt_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Section 2 — Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_2_image_alt_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Section 2 — Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_3_image_alt_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Section 3 — Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='section_3_image_alt_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Section 3 — Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_250_image_alt_en',
            field=models.CharField(blank=True, help_text='ALT text for the €250K tier image.', max_length=200, null=True, verbose_name='€250K Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_250_image_alt_tr',
            field=models.CharField(blank=True, help_text='ALT text for the €250K tier image.', max_length=200, null=True, verbose_name='€250K Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_400_image_alt_en',
            field=models.CharField(blank=True, help_text='ALT text for the €400K tier image.', max_length=200, null=True, verbose_name='€400K Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_400_image_alt_tr',
            field=models.CharField(blank=True, help_text='ALT text for the €400K tier image.', max_length=200, null=True, verbose_name='€400K Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_800_image_alt_en',
            field=models.CharField(blank=True, help_text='ALT text for the €800K tier image.', max_length=200, null=True, verbose_name='€800K Image ALT Text'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='tier_800_image_alt_tr',
            field=models.CharField(blank=True, help_text='ALT text for the €800K tier image.', max_length=200, null=True, verbose_name='€800K Image ALT Text'),
        ),
        migrations.AddField(
            model_name='office',
            name='address_en',
            field=models.TextField(null=True, verbose_name='Full Address'),
        ),
        migrations.AddField(
            model_name='office',
            name='address_tr',
            field=models.TextField(null=True, verbose_name='Full Address'),
        ),
        migrations.AddField(
            model_name='office',
            name='city_en',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='office',
            name='city_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='office',
            name='country_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='office',
            name='country_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='propertiespagesettings',
            name='hero_badge_en',
            field=models.CharField(default='Investment Opportunities', max_length=100, null=True, verbose_name='Hero Badge Text'),
        ),
        migrations.AddField(
            model_name='propertiespagesettings',
            name='hero_badge_tr',
            field=models.CharField(default='Investment Opportunities', max_length=100, null=True, verbose_name='Hero Badge Text'),
        ),
        migrations.AddField(
            model_name='propertiespagesettings',
            name='hero_subtitle_en',
            field=models.TextField(default='With property investment in Greece, you can both invest and secure permanent residency in Europe', null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='propertiespagesettings',
            name='hero_subtitle_tr',
            field=models.TextField(default='With property investment in Greece, you can both invest and secure permanent residency in Europe', null=True, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='propertiespagesettings',
            name='hero_title_en',
            field=models.CharField(default='Adonis Residential Developments', max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='propertiespagesettings',
            name='hero_title_tr',
            field=models.CharField(default='Adonis Residential Developments', max_length=200, null=True, verbose_name='Hero Title'),
        ),
        migrations.AddField(
            model_name='propertiespagesettings',
            name='intro_text_en',
            field=models.TextField(default='Adonis carefully selects the finest locations in Athens to design residential projects that bring you a luxurious lifestyle.', null=True, verbose_name='Intro Text'),
        ),
        migrations.AddField(
            model_name='propertiespagesettings',
            name='intro_text_tr',
            field=models.TextField(default='Adonis carefully selects the finest locations in Athens to design residential projects that bring you a luxurious lifestyle.', null=True, verbose_name='Intro Text'),
        ),
        migrations.AddField(
            model_name='propertiespagesettings',
            name='intro_title_en',
            field=models.CharField(default='A Luxury Experience in the Heart of Athens', max_length=200, null=True, verbose_name='Intro Title'),
        ),
        migrations.AddField(
            model_name='propertiespagesettings',
            name='intro_title_tr',
            field=models.CharField(default='A Luxury Experience in the Heart of Athens', max_length=200, null=True, verbose_name='Intro Title'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Short Bio'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Short Bio'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Position / Title'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Position / Title'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image ALT Text'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_alt_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image ALT Text'),
        ),
    ]
