# Generated by Django 4.2.28 on 2026-03-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_copy_en_data_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='short_video_urls',
            field=models.TextField(blank=True, help_text='Paste one YouTube Shorts URL per line. Supports youtube.com/shorts/ID, youtu.be/ID, and youtube.com/watch?v=ID formats.', verbose_name='YouTube Shorts URLs'),
        ),
    ]
