# Generated by Django 4.2.28 on 2026-03-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_short_video_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='short_video_url_1',
            field=models.URLField(blank=True, help_text='Paste a YouTube Shorts URL (youtube.com/shorts/ID or youtu.be/ID).', max_length=500, verbose_name='Short Video 1'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='short_video_url_2',
            field=models.URLField(blank=True, help_text='Paste a YouTube Shorts URL.', max_length=500, verbose_name='Short Video 2'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='short_video_url_3',
            field=models.URLField(blank=True, help_text='Paste a YouTube Shorts URL.', max_length=500, verbose_name='Short Video 3'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='short_video_url_4',
            field=models.URLField(blank=True, help_text='Paste a YouTube Shorts URL.', max_length=500, verbose_name='Short Video 4'),
        ),
        migrations.AddField(
            model_name='goldenvisalandingpage',
            name='short_video_url_5',
            field=models.URLField(blank=True, help_text='Paste a YouTube Shorts URL.', max_length=500, verbose_name='Short Video 5'),
        ),
        migrations.AlterField(
            model_name='goldenvisalandingpage',
            name='short_video_urls',
            field=models.TextField(blank=True, help_text='Legacy field — use the 5 individual fields below instead.', verbose_name='YouTube Shorts URLs (legacy)'),
        ),
    ]
