# Generated by Django 4.2.28 on 2026-03-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0053_add_short_video_url_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('old_slug', models.SlugField(help_text='The previous slug that should redirect to the current one.', max_length=255, verbose_name='Old slug')),
                ('language', models.CharField(default='en', help_text='Language code of the slug (en / tr).', max_length=5, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'Slug redirect',
                'verbose_name_plural': 'Slug redirects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['old_slug', 'content_type'], name='core_slughi_old_slu_727a1a_idx')],
                'unique_together': {('content_type', 'old_slug', 'language')},
            },
        ),
    ]
