# Generated by Django 4.2.29 on 2026-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_fa_tier_image_alt_cta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_1_image_alt',
            field=models.CharField(blank=True, help_text='برای SEO و accessibility.', max_length=200, verbose_name='متن جایگزین تصویر کارت اول (ALT)'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_1_long_desc',
            field=models.TextField(blank=True, help_text='متن کامل که در پنل کشویی «جزئیات بیشتر» نمایش داده می\u200cشود.', verbose_name='توضیح کامل کارت اول'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_1_price_amount',
            field=models.CharField(blank=True, help_text='مثال: €250,000', max_length=80, verbose_name='مبلغ قیمت کارت اول'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_1_price_label',
            field=models.CharField(blank=True, help_text='مثال: شروع از', max_length=80, verbose_name='متن برچسب قیمت کارت اول'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_1_short_desc',
            field=models.CharField(blank=True, help_text='۱ تا ۲ خط توضیح که روی کارت نمایش داده می\u200cشود.', max_length=320, verbose_name='توضیح کوتاه کارت اول'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_1_title',
            field=models.CharField(blank=True, help_text='عنوان فارسی کارت اول. خالی بگذارید تا از ترجمه خودکار استفاده شود.', max_length=220, verbose_name='عنوان کارت اول'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_2_long_desc',
            field=models.TextField(blank=True, help_text='متن کامل که در پنل کشویی «جزئیات بیشتر» نمایش داده می\u200cشود.', verbose_name='توضیح کامل کارت دوم'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_2_price_amount',
            field=models.CharField(blank=True, help_text='مثال: €400,000', max_length=80, verbose_name='مبلغ قیمت کارت دوم'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_2_price_label',
            field=models.CharField(blank=True, help_text='مثال: شروع از', max_length=80, verbose_name='متن برچسب قیمت کارت دوم'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_2_short_desc',
            field=models.CharField(blank=True, help_text='۱ تا ۲ خط توضیح که روی کارت نمایش داده می\u200cشود.', max_length=320, verbose_name='توضیح کوتاه کارت دوم'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_2_title',
            field=models.CharField(blank=True, help_text='عنوان فارسی کارت دوم. خالی بگذارید تا از ترجمه خودکار استفاده شود.', max_length=220, verbose_name='عنوان کارت دوم'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_3_long_desc',
            field=models.TextField(blank=True, help_text='متن کامل که در پنل کشویی «جزئیات بیشتر» نمایش داده می\u200cشود.', verbose_name='توضیح کامل کارت سوم'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_3_price_amount',
            field=models.CharField(blank=True, help_text='مثال: €800,000', max_length=80, verbose_name='مبلغ قیمت کارت سوم'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_3_price_label',
            field=models.CharField(blank=True, help_text='مثال: شروع از', max_length=80, verbose_name='متن برچسب قیمت کارت سوم'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_3_short_desc',
            field=models.CharField(blank=True, help_text='۱ تا ۲ خط توضیح که روی کارت نمایش داده می\u200cشود.', max_length=320, verbose_name='توضیح کوتاه کارت سوم'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_3_title',
            field=models.CharField(blank=True, help_text='عنوان فارسی کارت سوم. خالی بگذارید تا از ترجمه خودکار استفاده شود.', max_length=220, verbose_name='عنوان کارت سوم'),
        ),
    ]
