# Generated by Django 4.2.29 on 2026-03-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_fa_tier_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='own_shorts_more_url',
            field=models.URLField(blank=True, help_text='لینک کانال یا پلی\u200cلیست یوتیوب آدونیس. اگر خالی باشد دکمه نمایش داده نمی\u200cشود.', max_length=500, verbose_name='لینک «مشاهده ویدیوهای بیشتر» — ردیف اول'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='testimonial_shorts_more_url',
            field=models.URLField(blank=True, help_text='لینک پلی\u200cلیست یا کانال یوتیوب نظرات مشتریان. اگر خالی باشد دکمه نمایش داده نمی\u200cشود.', max_length=500, verbose_name='لینک «مشاهده ویدیوهای بیشتر» — ردیف دوم'),
        ),
    ]
