# Generated by Django 4.2.29 on 2026-03-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_fa_yt_more_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='fa_instagram_url',
            field=models.URLField(blank=True, help_text='پروفایل اینستاگرام فارسی. اگر خالی باشد از لینک پیش\u200cفرض سایت استفاده می\u200cشود.', max_length=500, verbose_name='اینستاگرام (اختصاصی صفحه فارسی)'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='fa_linkedin_url',
            field=models.URLField(blank=True, help_text='پروفایل لینکدین. اگر خالی باشد از لینک پیش\u200cفرض سایت استفاده می\u200cشود.', max_length=500, verbose_name='لینکدین (اختصاصی صفحه فارسی)'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='fa_telegram_url',
            field=models.URLField(blank=True, help_text='لینک کانال یا آی\u200cدی تلگرام (مثال: https://t.me/adonisgroup).', max_length=500, verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='fa_whatsapp_number',
            field=models.CharField(blank=True, help_text='شماره واتساپ با کد کشور (مثال: +306985989596). اگر خالی باشد از شماره پیش\u200cفرض سایت استفاده می\u200cشود.', max_length=30, verbose_name='شماره واتساپ (اختصاصی صفحه فارسی)'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='fa_x_url',
            field=models.URLField(blank=True, help_text='پروفایل X / Twitter. اگر خالی باشد از لینک پیش\u200cفرض سایت استفاده می\u200cشود.', max_length=500, verbose_name='X (توییتر) — اختصاصی صفحه فارسی'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='fa_youtube_url',
            field=models.URLField(blank=True, help_text='کانال یوتیوب فارسی. اگر خالی باشد از لینک پیش\u200cفرض سایت استفاده می\u200cشود.', max_length=500, verbose_name='یوتیوب (اختصاصی صفحه فارسی)'),
        ),
    ]
