# Generated by Django 4.2.29 on 2026-03-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_fa_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='whatsapp_number',
            field=models.CharField(default='+306985989596', help_text='WhatsApp number or full link (e.g. https://wa.me/message/...)', max_length=100, verbose_name='WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='fa_whatsapp_number',
            field=models.CharField(blank=True, help_text='شماره واتساپ یا لینک کامل (مثال: https://wa.me/message/...). اگر خالی باشد از شماره پیش\u200cفرض سایت استفاده می\u200cشود.', max_length=100, verbose_name='شماره یا لینک واتساپ (اختصاصی صفحه فارسی)'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_1_price_amount',
            field=models.CharField(blank=True, help_text='عددی که روی badge قیمت نمایش داده می\u200cشود. مثال: €250,000 — اعداد فارسی نمایش داده می\u200cشوند.', max_length=80, verbose_name='مبلغ قیمت کارت اول (badge)'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_1_price_label',
            field=models.CharField(blank=True, help_text='متن کوچکی که بالای عدد قیمت نمایش داده می\u200cشود. مثال: شروع از', max_length=80, verbose_name='متن بالای قیمت کارت اول'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_2_price_amount',
            field=models.CharField(blank=True, help_text='عددی که روی badge قیمت نمایش داده می\u200cشود. مثال: €400,000 — اعداد فارسی نمایش داده می\u200cشوند.', max_length=80, verbose_name='مبلغ قیمت کارت دوم (badge)'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_2_price_label',
            field=models.CharField(blank=True, help_text='متن کوچکی که بالای عدد قیمت نمایش داده می\u200cشود. مثال: شروع از', max_length=80, verbose_name='متن بالای قیمت کارت دوم'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_3_price_amount',
            field=models.CharField(blank=True, help_text='عددی که روی badge قیمت نمایش داده می\u200cشود. مثال: €800,000 — اعداد فارسی نمایش داده می\u200cشوند.', max_length=80, verbose_name='مبلغ قیمت کارت سوم (badge)'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='tier_3_price_label',
            field=models.CharField(blank=True, help_text='متن کوچکی که بالای عدد قیمت نمایش داده می\u200cشود. مثال: شروع از', max_length=80, verbose_name='متن بالای قیمت کارت سوم'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='whatsapp_number',
            field=models.CharField(default='+306985989596', help_text='WhatsApp number or full link (e.g. https://wa.me/message/...)', max_length=100, verbose_name='WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='+306985989596', max_length=100),
        ),
    ]
