# Generated by Django 4.2.29 on 2026-04-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_blogcategory_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='hero_subtitle_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ فونت ساب\u200cتایتل هیرو'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='hero_subtitle_font_size',
            field=models.CharField(default='20px', max_length=10, verbose_name='سایز فونت ساب\u200cتایتل هیرو'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='hero_title_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ فونت تیتر هیرو'),
        ),
        migrations.AlterField(
            model_name='goldenvisafalandingpage',
            name='hero_title_font_size',
            field=models.CharField(default='48px', max_length=10, verbose_name='سایز فونت تیتر هیرو'),
        ),
    ]
