# Generated by Django 4.2.28 on 2026-04-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_fa_hero_font_size_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenVisaFaProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مرحله')),
                ('description', models.TextField(blank=True, verbose_name='توضیح مرحله')),
                ('step_number', models.PositiveSmallIntegerField(verbose_name='شماره مرحله')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fa_process_steps/', verbose_name='تصویر مرتبط')),
                ('icon', models.CharField(blank=True, help_text='مثلاً: fas fa-passport', max_length=100, verbose_name='آیکن (Font Awesome class)')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مرحله گلدن ویزا (فارسی)',
                'verbose_name_plural': 'مراحل گلدن ویزا (فارسی)',
                'ordering': ['display_order', 'step_number'],
            },
        ),
    ]
