# Generated by Django 4.2.28 on 2026-04-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_goldenvisafafprocessstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='source',
            field=models.CharField(blank=True, max_length=60, verbose_name='Source'),
        ),
    ]
