# Generated by Django 4.2.29 on 2026-04-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_contactsubmission_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_1_subtitle',
            field=models.TextField(blank=True, verbose_name='مرحله ۱ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_1_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='مرحله ۱ – عنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_2_subtitle',
            field=models.TextField(blank=True, verbose_name='مرحله ۲ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_2_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='مرحله ۲ – عنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_3_subtitle',
            field=models.TextField(blank=True, verbose_name='مرحله ۳ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_3_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='مرحله ۳ – عنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_4_subtitle',
            field=models.TextField(blank=True, verbose_name='مرحله ۴ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_4_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='مرحله ۴ – عنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_5_subtitle',
            field=models.TextField(blank=True, verbose_name='مرحله ۵ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_5_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='مرحله ۵ – عنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_6_subtitle',
            field=models.TextField(blank=True, verbose_name='مرحله ۶ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='step_6_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='مرحله ۶ – عنوان'),
        ),
    ]
