# Generated by Django 4.2.29 on 2026-04-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_goldenvisafalandingpage_6steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_1_icon',
            field=models.CharField(blank=True, default='🏆', max_length=10, verbose_name='مزیت ۱ – آیکون'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_1_text',
            field=models.TextField(blank=True, default='بیش از یک دهه حضور فعال در بازار ملک یونان و راهنمایی صدها خانواده ایرانی.', verbose_name='مزیت ۱ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_1_title',
            field=models.CharField(blank=True, default='تجربه ۱۰+ ساله', max_length=120, verbose_name='مزیت ۱ – عنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_2_icon',
            field=models.CharField(blank=True, default='🤝', max_length=10, verbose_name='مزیت ۲ – آیکون'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_2_text',
            field=models.TextField(blank=True, default='از انتخاب ملک تا دریافت کارت اقامت، تمامی مراحل را پیش روی شما مدیریت می\u200cکنیم.', verbose_name='مزیت ۲ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_2_title',
            field=models.CharField(blank=True, default='خدمات کامل زیر یک سقف', max_length=120, verbose_name='مزیت ۲ – عنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_3_icon',
            field=models.CharField(blank=True, default='🛡️', max_length=10, verbose_name='مزیت ۳ – آیکون'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_3_text',
            field=models.TextField(blank=True, default='تمام معاملات با پشتوانه حقوقی کامل و وکلای مجرب یونانی انجام می\u200cشود.', verbose_name='مزیت ۳ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_3_title',
            field=models.CharField(blank=True, default='امنیت سرمایه\u200cگذاری', max_length=120, verbose_name='مزیت ۳ – عنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_4_icon',
            field=models.CharField(blank=True, default='🌍', max_length=10, verbose_name='مزیت ۴ – آیکون'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_4_text',
            field=models.TextField(blank=True, default='تیم ما به زبان فارسی در کنار شماست و هیچ سوالی بی\u200cپاسخ نمی\u200cماند.', verbose_name='مزیت ۴ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_4_title',
            field=models.CharField(blank=True, default='پشتیبانی فارسی\u200cزبان', max_length=120, verbose_name='مزیت ۴ – عنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_5_icon',
            field=models.CharField(blank=True, default='🏙️', max_length=10, verbose_name='مزیت ۵ – آیکون'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_5_text',
            field=models.TextField(blank=True, verbose_name='مزیت ۵ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_5_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='مزیت ۵ – عنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_6_icon',
            field=models.CharField(blank=True, default='⭐', max_length=10, verbose_name='مزیت ۶ – آیکون'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_6_text',
            field=models.TextField(blank=True, verbose_name='مزیت ۶ – توضیح'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_6_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='مزیت ۶ – عنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_section_subtitle',
            field=models.CharField(blank=True, default='با بیش از یک دهه تجربه در بازار ملک یونان، آدونیس بهترین انتخاب برای سفر سرمایه\u200cگذاری شماست.', max_length=400, verbose_name='سکشن مزایا – زیرعنوان'),
        ),
        migrations.AddField(
            model_name='goldenvisafalandingpage',
            name='adonis_feat_section_title',
            field=models.CharField(blank=True, default='چرا آدونیس گروپ؟', max_length=220, verbose_name='سکشن مزایا – عنوان'),
        ),
    ]
