# Generated by Django 4.2.29 on 2026-04-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_goldenvisafa_adonis_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='request_type',
            field=models.CharField(choices=[('general', 'General'), ('property', 'Property'), ('golden_visa', 'Golden Visa'), ('customer', 'Customer'), ('agent', 'Agent'), ('partnership', 'Partnership'), ('other', 'Other')], default='general', max_length=20, verbose_name='Request Type'),
        ),
        migrations.AlterField(
            model_name='partnerlead',
            name='partner_type',
            field=models.CharField(choices=[('broker', 'Broker'), ('agent', 'Agent'), ('lawyer', 'Lawyer'), ('client', 'Client'), ('accountant', 'Accountant'), ('other', 'Other')], max_length=20, verbose_name='Partner Type'),
        ),
    ]
