# Generated by Django 4.2.28 on 2026-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_add_request_type_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarLandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='ویژه ایرانیان مقیم امارات و ترکیه', max_length=200, verbose_name='Hero Badge')),
                ('hero_title', models.CharField(default='وبینار تخصصی اقامت و سرمایه\u200cگذاری اروپا', max_length=300, verbose_name='Hero Title')),
                ('hero_subtitle', models.TextField(default='اخذ اقامت دائم اروپا\nبرای سرمایه\u200cگذاران ایرانی', help_text='Large secondary heading shown under the main hero title. Use line breaks for multi-line display.', verbose_name='Hero Subtitle')),
                ('hero_description', models.TextField(default='اگر در امارات یا ترکیه زندگی می\u200cکنید و به دنبال یک مسیر مطمئن برای سرمایه\u200cگذاری، دریافت اقامت اروپا و ساخت آینده\u200cای امن\u200cتر برای خانواده خود هستید، این وبینار برای شماست.', verbose_name='Hero Description')),
                ('hero_background_image', models.ImageField(blank=True, help_text='Cinematic Dubai skyline / sunset image. If empty, an elegant gradient is used.', null=True, upload_to='webinar_landing/', verbose_name='Hero Background Image')),
                ('webinar_date_text', models.CharField(default='پنجشنبه — 21 May 2026 — 31 اردیبهشت 1405', max_length=200, verbose_name='Webinar Date Text')),
                ('webinar_time_text', models.CharField(default='ساعت ۲۰ — به وقت امارات', max_length=160, verbose_name='Webinar Time Text')),
                ('webinar_format_text', models.CharField(default='برگزاری آنلاین — ظرفیت محدود', max_length=160, verbose_name='Webinar Format Text')),
                ('benefit_1_title', models.CharField(default='اقامت دائم اروپا', max_length=160, verbose_name='Benefit 1 — Title')),
                ('benefit_1_text', models.CharField(default='برای شما و خانواده', max_length=240, verbose_name='Benefit 1 — Subtitle')),
                ('benefit_2_title', models.CharField(default='دسترسی به بازار اروپا', max_length=160, verbose_name='Benefit 2 — Title')),
                ('benefit_2_text', models.CharField(default='و فرصت\u200cهای بین\u200cالمللی', max_length=240, verbose_name='Benefit 2 — Subtitle')),
                ('benefit_3_title', models.CharField(default='فرصت\u200cهای بیشتر', max_length=160, verbose_name='Benefit 3 — Title')),
                ('benefit_3_text', models.CharField(default='برای سرمایه\u200cگذاری و رشد', max_length=240, verbose_name='Benefit 3 — Subtitle')),
                ('intro_title', models.CharField(default='چرا این وبینار مهم است؟', max_length=200, verbose_name='Intro Section Title')),
                ('intro_description', models.TextField(default='در این وبینار، به\u200cصورت شفاف درباره روش\u200cهای دریافت اقامت اروپا، شرایط واقعی سرمایه\u200cگذاری در یونان، مزایا، ریسک\u200cها و نکات مهم قبل از تصمیم\u200cگیری صحبت خواهیم کرد.', verbose_name='Intro Section Description')),
                ('intro_video', models.FileField(blank=True, help_text='Short MP4/WEBM intro. If empty, an elegant placeholder with an animated play button is shown.', null=True, upload_to='webinar_landing/', verbose_name='Intro Video')),
                ('form_title', models.CharField(default='ثبت\u200cنام در وبینار', max_length=200, verbose_name='Form Title')),
                ('form_button_text', models.CharField(default='ثبت\u200cنام در وبینار', max_length=120, verbose_name='Form Button Text')),
                ('success_title', models.CharField(default='ثبت\u200cنام شما با موفقیت انجام شد.', max_length=200, verbose_name='Success — Title')),
                ('success_text', models.TextField(default='شما در وبینار تاریخ ۲۱ می ۲۰۲۶ ویژه اقامت و سرمایه\u200cگذاری اروپا ثبت\u200cنام شدید.\n\nاطلاعات و لینک ورود به وبینار برای شما ارسال خواهد شد.', verbose_name='Success — Body')),
                ('success_button_text', models.CharField(default='متوجه شدم', max_length=80, verbose_name='Success — Button')),
                ('cta_title', models.TextField(default='ظرفیت این وبینار محدود است.\nهمین حالا ثبت\u200cنام کنید.', help_text='Use line breaks for the dramatic two-line CTA heading.', verbose_name='Final CTA Title')),
                ('cta_button_text', models.CharField(default='رزرو جایگاه در وبینار', max_length=120, verbose_name='Final CTA Button')),
                ('active_status', models.BooleanField(default=True, help_text='Uncheck to hide the /webinar/ page (returns 404).', verbose_name='Page Active')),
                ('meta_title', models.CharField(blank=True, default='وبینار تخصصی اقامت و سرمایه\u200cگذاری اروپا', max_length=180, verbose_name='SEO Meta Title')),
                ('meta_description', models.CharField(blank=True, default='وبینار تخصصی اقامت دائم اروپا و سرمایه\u200cگذاری در یونان ویژه ایرانیان مقیم امارات و ترکیه — ظرفیت محدود.', max_length=300, verbose_name='SEO Meta Description')),
            ],
            options={
                'verbose_name': 'Webinar Landing — Settings',
                'verbose_name_plural': 'Webinar Landing — Settings',
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=40, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered At')),
            ],
            options={
                'verbose_name': 'Webinar Registration',
                'verbose_name_plural': 'Webinar Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
