# Generated by Django 4.2.28 on 2026-05-08 13:01

from django.db import migrations, models


_RICHTEXT_FIELDS = (
    'hero_subtitle',
    'hero_description',
    'intro_description',
    'success_text',
    'cta_title',
)


def _convert_plain_to_html(text: str) -> str:
    """Convert plain-text content (with \\n line breaks) into <p>...</p> HTML.

    Skips conversion if the value already looks like HTML (contains a tag),
    so re-running the migration is safe.
    """
    if not text:
        return text
    s = str(text)
    if '<' in s and '>' in s:
        return s  # Already HTML — leave alone.
    paragraphs = [chunk.strip() for chunk in s.replace('\r\n', '\n').split('\n\n')]
    out_paragraphs = []
    for para in paragraphs:
        if not para:
            continue
        # Convert single newlines inside a paragraph to <br>
        inner = para.replace('\n', '<br>')
        out_paragraphs.append(f'<p>{inner}</p>')
    return ''.join(out_paragraphs) if out_paragraphs else s


def _forwards_convert_to_html(apps, schema_editor):
    Settings = apps.get_model('core', 'WebinarLandingSettings')
    for row in Settings.objects.all():
        changed = False
        for field in _RICHTEXT_FIELDS:
            current = getattr(row, field, '') or ''
            new_val = _convert_plain_to_html(current)
            if new_val != current:
                setattr(row, field, new_val)
                changed = True
        if changed:
            row.save(update_fields=list(_RICHTEXT_FIELDS))


def _backwards_noop(apps, schema_editor):
    """Reverting only restores the schema — content stays HTML."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_webinar_landing_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarlandingsettings',
            name='cta_title',
            field=models.TextField(default='<p>ظرفیت این وبینار محدود است.</p><p>همین حالا ثبت\u200cنام کنید.</p>', help_text='Each paragraph becomes a separate display line. The second paragraph is shown in gold.', verbose_name='Final CTA Title'),
        ),
        migrations.AlterField(
            model_name='webinarlandingsettings',
            name='hero_description',
            field=models.TextField(default='<p>اگر در امارات یا ترکیه زندگی می\u200cکنید و به دنبال یک مسیر مطمئن برای سرمایه\u200cگذاری، دریافت اقامت اروپا و ساخت آینده\u200cای امن\u200cتر برای خانواده خود هستید، این وبینار برای شماست.</p>', verbose_name='Hero Description'),
        ),
        migrations.AlterField(
            model_name='webinarlandingsettings',
            name='hero_subtitle',
            field=models.TextField(default='<p>اخذ اقامت دائم اروپا</p><p>برای سرمایه\u200cگذاران ایرانی</p>', help_text='Large secondary heading. Each paragraph becomes a separate display line.', verbose_name='Hero Subtitle'),
        ),
        migrations.AlterField(
            model_name='webinarlandingsettings',
            name='intro_description',
            field=models.TextField(default='<p>در این وبینار، به\u200cصورت شفاف درباره روش\u200cهای دریافت اقامت اروپا، شرایط واقعی سرمایه\u200cگذاری در یونان، مزایا، ریسک\u200cها و نکات مهم قبل از تصمیم\u200cگیری صحبت خواهیم کرد.</p>', verbose_name='Intro Section Description'),
        ),
        migrations.AlterField(
            model_name='webinarlandingsettings',
            name='success_text',
            field=models.TextField(default='<p>شما در وبینار تاریخ ۲۱ می ۲۰۲۶ ویژه اقامت و سرمایه\u200cگذاری اروپا ثبت\u200cنام شدید.</p><p>اطلاعات و لینک ورود به وبینار برای شما ارسال خواهد شد.</p>', verbose_name='Success — Body'),
        ),
        migrations.RunPython(_forwards_convert_to_html, _backwards_noop),
    ]
