# Generated by Django 4.2.28 on 2026-05-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_webinar_richtext_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarlandingsettings',
            name='hero_speaker_name',
            field=models.CharField(default='MEISAM SABOUR | PhD', help_text='Shown in gold under the speaker photo. Latin script recommended.', max_length=200, verbose_name='Hero Speaker Name'),
        ),
        migrations.AddField(
            model_name='webinarlandingsettings',
            name='hero_speaker_photo',
            field=models.ImageField(blank=True, help_text='Portrait of the host/speaker. PNG with transparent background recommended (at least 800×1100 px). If empty, the bundled Dr. Meisam Sabour image is used.', null=True, upload_to='webinar_landing/speakers/', verbose_name='Hero Speaker Photo'),
        ),
        migrations.AddField(
            model_name='webinarlandingsettings',
            name='hero_speaker_title',
            field=models.CharField(default='هم\u200cمؤسس ADONIS', help_text='Short role/credential line under the speaker name.', max_length=200, verbose_name='Hero Speaker Title'),
        ),
    ]
