# Generated by Django 4.2.28 on 2026-05-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_webinar_speaker_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaNewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_video', models.FileField(blank=True, help_text='ویدیوی سینمایی برای صفحه پیش\u200cنمایش فارسی /fa-new/ . فرمت پیشنهادی: MP4 (H.264) با faststart. حداکثر ۵۰۰ مگابایت.', null=True, upload_to='fa-new/', verbose_name='ویدیو هیرو فارسی (Hero Video — fa-new)')),
                ('hero_video_poster', models.ImageField(blank=True, help_text='تصویر فریم اول که قبل از لود شدن ویدیو نشان داده می\u200cشود.', null=True, upload_to='fa-new/', verbose_name='پوستر ویدیو (Poster Image)')),
                ('note', models.CharField(blank=True, help_text='فقط برای ادمین، روی سایت نمایش داده نمی\u200cشود.', max_length=200, verbose_name='یادداشت داخلی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': '/fa-new/ — تنظیمات پیش\u200cنمایش فارسی',
                'verbose_name_plural': '/fa-new/ — تنظیمات پیش\u200cنمایش فارسی',
            },
        ),
    ]
