from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_fa_new_hero_slides'),
    ]

    operations = [
        # ── Overlay 1 ─────────────────────────────────────────────────────────
        migrations.AddField('FaNewSettings', 'o1_eyebrow',
            models.CharField(blank=True, default='ADONIS · ATHENS', max_length=100,
                             verbose_name='اسلاید ۱ — متن کوچک بالا')),
        migrations.AddField('FaNewSettings', 'o1_title',
            models.CharField(blank=True, default='سرمایه‌گذاری در یونان', max_length=250,
                             verbose_name='اسلاید ۱ — عنوان اصلی')),
        migrations.AddField('FaNewSettings', 'o1_highlight',
            models.CharField(blank=True, default='یونان', max_length=100,
                             verbose_name='اسلاید ۱ — کلمه طلایی')),
        migrations.AddField('FaNewSettings', 'o1_subtitle',
            models.TextField(blank=True, default='آغاز یک مسیر مطمئن برای اقامت اروپا',
                             verbose_name='اسلاید ۱ — زیرعنوان')),
        migrations.AddField('FaNewSettings', 'o1_start',
            models.FloatField(default=0, verbose_name='اسلاید ۱ — شروع (%)')),
        migrations.AddField('FaNewSettings', 'o1_end',
            models.FloatField(default=30, verbose_name='اسلاید ۱ — پایان (%)')),

        # ── Overlay 2 ─────────────────────────────────────────────────────────
        migrations.AddField('FaNewSettings', 'o2_eyebrow',
            models.CharField(blank=True, default='خانه · آتن', max_length=100,
                             verbose_name='اسلاید ۲ — متن کوچک بالا')),
        migrations.AddField('FaNewSettings', 'o2_title',
            models.CharField(blank=True, default='خانه‌ای در آتن، آینده‌ای در اروپا',
                             max_length=250, verbose_name='اسلاید ۲ — عنوان اصلی')),
        migrations.AddField('FaNewSettings', 'o2_highlight',
            models.CharField(blank=True, default='اروپا', max_length=100,
                             verbose_name='اسلاید ۲ — کلمه طلایی')),
        migrations.AddField('FaNewSettings', 'o2_subtitle',
            models.TextField(blank=True, default='خرید ملک، دریافت اقامت، ساختن یک زندگی جدید',
                             verbose_name='اسلاید ۲ — زیرعنوان')),
        migrations.AddField('FaNewSettings', 'o2_start',
            models.FloatField(default=30, verbose_name='اسلاید ۲ — شروع (%)')),
        migrations.AddField('FaNewSettings', 'o2_end',
            models.FloatField(default=60, verbose_name='اسلاید ۲ — پایان (%)')),

        # ── Overlay 3 ─────────────────────────────────────────────────────────
        migrations.AddField('FaNewSettings', 'o3_eyebrow',
            models.CharField(blank=True, default='خانواده · پوشش کامل', max_length=100,
                             verbose_name='اسلاید ۳ — متن کوچک بالا')),
        migrations.AddField('FaNewSettings', 'o3_title',
            models.CharField(blank=True, default='اقامت یونان برای خانواده شما',
                             max_length=250, verbose_name='اسلاید ۳ — عنوان اصلی')),
        migrations.AddField('FaNewSettings', 'o3_highlight',
            models.CharField(blank=True, default='خانواده شما', max_length=100,
                             verbose_name='اسلاید ۳ — کلمه طلایی')),
        migrations.AddField('FaNewSettings', 'o3_subtitle',
            models.TextField(blank=True, default='همراه با همسر، فرزندان و والدین دو طرف',
                             verbose_name='اسلاید ۳ — زیرعنوان')),
        migrations.AddField('FaNewSettings', 'o3_start',
            models.FloatField(default=60, verbose_name='اسلاید ۳ — شروع (%)')),
        migrations.AddField('FaNewSettings', 'o3_end',
            models.FloatField(default=85, verbose_name='اسلاید ۳ — پایان (%)')),

        # ── Overlay 4 ─────────────────────────────────────────────────────────
        migrations.AddField('FaNewSettings', 'o4_eyebrow',
            models.CharField(blank=True, default='گام بعدی', max_length=100,
                             verbose_name='اسلاید ۴ — متن کوچک بالا')),
        migrations.AddField('FaNewSettings', 'o4_title',
            models.CharField(blank=True, default='با ADONIS قدم بعدی را بردارید',
                             max_length=250, verbose_name='اسلاید ۴ — عنوان اصلی')),
        migrations.AddField('FaNewSettings', 'o4_highlight',
            models.CharField(blank=True, default='ADONIS', max_length=100,
                             verbose_name='اسلاید ۴ — کلمه طلایی')),
        migrations.AddField('FaNewSettings', 'o4_start',
            models.FloatField(default=85, verbose_name='اسلاید ۴ — شروع (%)')),
        migrations.AddField('FaNewSettings', 'o4_end',
            models.FloatField(default=101, verbose_name='اسلاید ۴ — پایان (%)')),

        # ── CTA Buttons ───────────────────────────────────────────────────────
        migrations.AddField('FaNewSettings', 'cta_primary_label',
            models.CharField(blank=True, default='دریافت مشاوره', max_length=80,
                             verbose_name='دکمه اول — متن')),
        migrations.AddField('FaNewSettings', 'cta_primary_url',
            models.CharField(blank=True, default='#fa-section-consult', max_length=300,
                             verbose_name='دکمه اول — لینک')),
        migrations.AddField('FaNewSettings', 'cta_secondary_label',
            models.CharField(blank=True, default='مشاهده پروژه‌ها', max_length=80,
                             verbose_name='دکمه دوم — متن')),
        migrations.AddField('FaNewSettings', 'cta_secondary_url',
            models.CharField(blank=True, default='#fa-section-projects', max_length=300,
                             verbose_name='دکمه دوم — لینک')),

        # ── Hero Colors ───────────────────────────────────────────────────────
        migrations.AddField('FaNewSettings', 'hero_text_color',
            models.CharField(blank=True, default='#ffffff', max_length=30,
                             verbose_name='رنگ عنوان‌ها')),
        migrations.AddField('FaNewSettings', 'hero_subtitle_color',
            models.CharField(blank=True, default='#cccccc', max_length=30,
                             verbose_name='رنگ زیرعنوان‌ها')),
        migrations.AddField('FaNewSettings', 'hero_accent_color',
            models.CharField(blank=True, default='#efd99a', max_length=30,
                             verbose_name='رنگ لهجه (طلایی)')),
        migrations.AddField('FaNewSettings', 'hero_scrim_color',
            models.CharField(blank=True, default='#060814', max_length=30,
                             verbose_name='رنگ پس‌زمینه تیره‌کننده')),
        migrations.AddField('FaNewSettings', 'hero_cta_primary_bg',
            models.CharField(blank=True, default='#efd99a', max_length=30,
                             verbose_name='دکمه اول — رنگ پس‌زمینه')),
        migrations.AddField('FaNewSettings', 'hero_cta_primary_text',
            models.CharField(blank=True, default='#1b1306', max_length=30,
                             verbose_name='دکمه اول — رنگ متن')),
        migrations.AddField('FaNewSettings', 'hero_cta_secondary_border',
            models.CharField(blank=True, default='#808080', max_length=30,
                             verbose_name='دکمه دوم — رنگ حاشیه')),
        migrations.AddField('FaNewSettings', 'hero_cta_secondary_text',
            models.CharField(blank=True, default='#ffffff', max_length=30,
                             verbose_name='دکمه دوم — رنگ متن')),
    ]
