# Generated by Django 4.2.28 on 2026-05-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_fanewsettings_hero_overlay_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaFooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='آدونیس | ADONIS', max_length=150, verbose_name='نام برند')),
                ('brand_tagline', models.CharField(blank=True, default='گروه توسعه و مشاوره اقامت در آتن', max_length=250, verbose_name='شعار / توضیح کوتاه برند')),
                ('footer_logo', models.ImageField(blank=True, help_text='PNG با پس\u200cزمینه شفاف — اختیاری. اگر خالی باشد از لوگوی هدر استفاده می\u200cشود.', null=True, upload_to='fa-new/footer/', verbose_name='لوگوی فوتر')),
                ('contact_title', models.CharField(blank=True, default='تماس', max_length=100, verbose_name='عنوان ستون تماس')),
                ('address', models.CharField(blank=True, default='آتن، آلیموس، خیابان پوزیدوناس، شماره ۷۸', max_length=300, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, default='+30 698 598 9596', max_length=50, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, default='info@adonisgroup.gr', max_length=254, verbose_name='ایمیل')),
                ('whatsapp_url', models.CharField(blank=True, default='https://wa.me/306985989596', help_text='مثال: https://wa.me/306985989596', max_length=300, verbose_name='لینک واتس\u200cاپ')),
                ('links_title', models.CharField(blank=True, default='دسترسی سریع', max_length=100, verbose_name='عنوان ستون لینک\u200cها')),
                ('copyright_text', models.CharField(blank=True, default='© آدونیس گروپ — همه حقوق محفوظ است.', max_length=300, verbose_name='متن کپی\u200cرایت')),
                ('footer_tag', models.CharField(blank=True, default='نسخه پیش\u200cنمایش فارسی · /fa-new/', help_text='متن کوچک سمت راست نوار پایین فوتر.', max_length=150, verbose_name='برچسب پایین فوتر')),
                ('instagram_url', models.CharField(blank=True, max_length=300, verbose_name='لینک اینستاگرام')),
                ('linkedin_url', models.CharField(blank=True, max_length=300, verbose_name='لینک لینکدین')),
                ('telegram_url', models.CharField(blank=True, max_length=300, verbose_name='لینک تلگرام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات فوتر صفحه فارسی',
                'verbose_name_plural': 'تنظیمات فوتر صفحه فارسی',
            },
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='header_logo',
            field=models.ImageField(blank=True, help_text='PNG با پس\u200cزمینه شفاف — ارتفاع ۶۰ تا ۱۲۰ پیکسل.', null=True, upload_to='fa-new/', verbose_name='لوگو هدر'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='hero_accent_color',
            field=models.CharField(blank=True, default='#efd99a', help_text='رنگ کلمه طلایی در عنوان\u200cها.', max_length=30, verbose_name='رنگ لهجه (طلایی)'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='hero_scrim_color',
            field=models.CharField(blank=True, default='#060814', help_text='رنگ لایه تیره روی ویدیو. معمولاً همرنگ پس\u200cزمینه سایت.', max_length=30, verbose_name='رنگ پس\u200cزمینه تیره\u200cکننده (scrim)'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='hero_text_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='رنگ H1/H2 روی هیرو. فرمت hex (#rrggbb).', max_length=30, verbose_name='رنگ عنوان\u200cها'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='MP4 (H.264) با faststart — حداکثر ۵۰۰ مگابایت.', null=True, upload_to='fa-new/', verbose_name='ویدیو هیرو'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='hero_video_poster',
            field=models.ImageField(blank=True, help_text='تصویر فریم اول که قبل از لود شدن ویدیو نشان داده می\u200cشود.', null=True, upload_to='fa-new/', verbose_name='پوستر ویدیو'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='note',
            field=models.CharField(blank=True, help_text='فقط برای ادمین — روی سایت نمایش داده نمی\u200cشود.', max_length=200, verbose_name='یادداشت داخلی'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='o1_end',
            field=models.FloatField(default=30, help_text='درصد پایان نمایش این اسلاید در اسکرول (۰ تا ۱۰۰)', verbose_name='اسلاید ۱ — پایان (%)'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='o1_highlight',
            field=models.CharField(blank=True, default='یونان', help_text='این کلمه باید دقیقاً در متن عنوان وجود داشته باشد.', max_length=100, verbose_name='اسلاید ۱ — کلمه طلایی'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='o1_start',
            field=models.FloatField(default=0, help_text='درصد شروع نمایش این اسلاید در اسکرول (۰ تا ۱۰۰)', verbose_name='اسلاید ۱ — شروع (%)'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='o1_title',
            field=models.CharField(blank=True, default='سرمایه\u200cگذاری در یونان', help_text='کلمه\u200cای که باید طلایی شود را در فیلد «کلمه طلایی» بنویسید.', max_length=250, verbose_name='اسلاید ۱ — عنوان اصلی'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='o4_end',
            field=models.FloatField(default=101, help_text='مقدار بیش از ۱۰۰ یعنی تا انتهای اسکرول نشان داده می\u200cشود.', verbose_name='اسلاید ۴ — پایان (%)'),
        ),
        migrations.AlterField(
            model_name='fanewsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.CreateModel(
            name='FaNavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='متنی که در منو نمایش داده می\u200cشود.', max_length=100, verbose_name='متن لینک')),
                ('url', models.CharField(help_text='آدرس URL یا anchor مثل #fa-section-why_greece یا https://example.com', max_length=500, verbose_name='لینک')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='عدد کوچک\u200cتر = چپ\u200cتر در نوار ناوبری', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='غیرفعال کردن این آیتم را از منو پنهان می\u200cکند.', verbose_name='فعال')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='باز کردن در تب جدید')),
                ('parent', models.ForeignKey(blank=True, help_text='اگر این آیتم زیرمنوی یک آیتم دیگر است، آن را اینجا انتخاب کنید.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.fanavmenuitem', verbose_name='زیرمنوی')),
            ],
            options={
                'verbose_name': 'آیتم منوی فارسی',
                'verbose_name_plural': 'منوی ناوبری صفحه فارسی',
                'ordering': ['order'],
            },
        ),
    ]
