# Generated by Django 4.2.30 on 2026-05-17 19:31

import django.core.validators
from django.db import migrations, models


def _seed_anchor_ids(apps, schema_editor):
    FaNewSection = apps.get_model('core', 'FaNewSection')
    for section in FaNewSection.objects.all().order_by('order', 'id'):
        if section.anchor_id:
            continue
        section.anchor_id = f'fa-section-{section.section_type}'.replace('_', '-')
        section.save(update_fields=['anchor_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_fa_nav_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fanewsection',
            options={'ordering': ['order'], 'verbose_name': 'سکشن صفحه اصلی فارسی', 'verbose_name_plural': 'بخش\u200cهای صفحه — مدیریت سکشن\u200cهای صفحه اصلی فارسی'},
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='accent_color',
            field=models.CharField(blank=True, default='#1E5AA8', max_length=30, verbose_name='accent color'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='anchor_id',
            field=models.SlugField(blank=True, help_text='شناسه یکتا برای لینک\u200cدهی داخل صفحه. مثال: fa-section-gateway', max_length=80, verbose_name='anchor id'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='background_color',
            field=models.CharField(blank=True, default='#071527', max_length=30, verbose_name='background color'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='fa-new/sections/backgrounds/', verbose_name='تصویر پس\u200cزمینه'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='background_image_alt',
            field=models.CharField(blank=True, max_length=220, verbose_name='alt تصویر پس\u200cزمینه'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='background_video',
            field=models.FileField(blank=True, null=True, upload_to='fa-new/sections/videos/', verbose_name='ویدیو پس\u200cزمینه'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='blur_intensity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='blur intensity'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='border_color',
            field=models.CharField(blank=True, default='rgba(11,31,58,0.1)', max_length=30, verbose_name='border color'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='border_radius',
            field=models.PositiveIntegerField(default=24, verbose_name='border radius'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_1_accent_color',
            field=models.CharField(blank=True, default='#1E5AA8', max_length=30, verbose_name='Card 1 accent color'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_1_cta_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Card 1 CTA link'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_1_cta_text',
            field=models.CharField(blank=True, max_length=120, verbose_name='Card 1 CTA text'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_1_description',
            field=models.TextField(blank=True, verbose_name='Card 1 description'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='fa-new/sections/cards/', verbose_name='Card 1 image'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_1_image_alt',
            field=models.CharField(blank=True, max_length=220, verbose_name='Card 1 image alt'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_1_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Card 1 label'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_1_subtitle',
            field=models.CharField(blank=True, max_length=260, verbose_name='Card 1 subtitle'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_1_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='Card 1 title'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_2_accent_color',
            field=models.CharField(blank=True, default='#1E5AA8', max_length=30, verbose_name='Card 2 accent color'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_2_cta_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Card 2 CTA link'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_2_cta_text',
            field=models.CharField(blank=True, max_length=120, verbose_name='Card 2 CTA text'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_2_description',
            field=models.TextField(blank=True, verbose_name='Card 2 description'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='fa-new/sections/cards/', verbose_name='Card 2 image'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_2_image_alt',
            field=models.CharField(blank=True, max_length=220, verbose_name='Card 2 image alt'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_2_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Card 2 label'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_2_subtitle',
            field=models.CharField(blank=True, max_length=260, verbose_name='Card 2 subtitle'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_2_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='Card 2 title'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_background',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=30, verbose_name='card background'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_gap',
            field=models.PositiveIntegerField(default=24, verbose_name='card gap'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='fa-new/sections/cards/', verbose_name='تصویر کارت اول'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_image_1_alt',
            field=models.CharField(blank=True, max_length=220, verbose_name='alt تصویر کارت اول'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='fa-new/sections/cards/', verbose_name='تصویر کارت دوم'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='card_image_2_alt',
            field=models.CharField(blank=True, max_length=220, verbose_name='alt تصویر کارت دوم'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='cta_primary_text',
            field=models.CharField(blank=True, max_length=120, verbose_name='متن CTA اول'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='cta_primary_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='لینک CTA اول'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='cta_secondary_text',
            field=models.CharField(blank=True, max_length=120, verbose_name='متن CTA دوم'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='cta_secondary_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='لینک CTA دوم'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='description',
            field=models.TextField(blank=True, help_text='توضیح اصلی سکشن', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='description_font_size',
            field=models.PositiveIntegerField(default=16, verbose_name='description font size'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='desktop_layout',
            field=models.CharField(choices=[('two_columns', '2 columns'), ('three_columns', '3 columns'), ('full_width', 'full width')], default='two_columns', max_length=20, verbose_name='desktop layout'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='font_weight',
            field=models.CharField(choices=[('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('800', '800'), ('900', '900')], default='700', max_length=3, verbose_name='font weight'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='gradient_color',
            field=models.CharField(blank=True, default='transparent', max_length=30, verbose_name='gradient color'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='hide_image_on_mobile',
            field=models.BooleanField(default=False, verbose_name='hide image on mobile'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='line_height',
            field=models.DecimalField(decimal_places=2, default=1.7, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.0)], verbose_name='line height'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='max_width_container',
            field=models.PositiveIntegerField(default=1240, verbose_name='max width container'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='mobile_layout',
            field=models.CharField(choices=[('stacked', 'stacked'), ('carousel', 'carousel')], default='stacked', max_length=20, verbose_name='mobile layout'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='section_name',
            field=models.CharField(blank=True, help_text='نام مدیریتی سکشن در پنل ادمین.', max_length=140, verbose_name='نام سکشن'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='section_padding_bottom',
            field=models.PositiveIntegerField(default=96, verbose_name='section padding bottom'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='section_padding_top',
            field=models.PositiveIntegerField(default=96, verbose_name='section padding top'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='shadow_intensity',
            field=models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='shadow intensity'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='show_on_desktop',
            field=models.BooleanField(default=True, verbose_name='نمایش در دسکتاپ'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='show_on_mobile',
            field=models.BooleanField(default=True, verbose_name='نمایش در موبایل'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='subtitle_font_size',
            field=models.PositiveIntegerField(default=22, verbose_name='subtitle font size'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='text_alignment',
            field=models.CharField(choices=[('right', 'right'), ('center', 'center'), ('left', 'left'), ('justify', 'justify')], default='center', max_length=10, verbose_name='text alignment'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='text_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=30, verbose_name='text color'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='title_font_size_desktop',
            field=models.PositiveIntegerField(default=42, verbose_name='title font size desktop'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='title_font_size_mobile',
            field=models.PositiveIntegerField(default=30, verbose_name='title font size mobile'),
        ),
        migrations.AddField(
            model_name='fanewsectionitem',
            name='accent_color',
            field=models.CharField(blank=True, default='#1E5AA8', max_length=30, verbose_name='رنگ accent'),
        ),
        migrations.AddField(
            model_name='fanewsectionitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیح'),
        ),
        migrations.AddField(
            model_name='fanewsectionitem',
            name='image_alt',
            field=models.CharField(blank=True, max_length=220, verbose_name='alt تصویر'),
        ),
        migrations.AddField(
            model_name='fanewsectionitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=240, verbose_name='زیرعنوان'),
        ),
        migrations.AlterField(
            model_name='fanewsection',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='برچسب کوچک بالای تیتر', max_length=100, verbose_name='eyebrow'),
        ),
        migrations.AlterField(
            model_name='fanewsection',
            name='section_type',
            field=models.CharField(choices=[('why_greece', 'چرا یونان؟'), ('why_adonis', 'چرا آدونیس؟'), ('routes', 'مسیرهای گلدن ویزا'), ('projects', 'پروژه\u200cهای منتخب'), ('process', 'فرآیند همکاری'), ('trust', 'اعتماد و تجربه'), ('consult', 'مشاوره رایگان'), ('gateway', 'گیت\u200cوی دو کارتی')], max_length=20, verbose_name='نوع بخش'),
        ),
        migrations.AlterField(
            model_name='fanewsection',
            name='subtitle',
            field=models.TextField(blank=True, help_text='زیرتیتر', verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='fanewsection',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='title'),
        ),
        migrations.RunPython(_seed_anchor_ids, migrations.RunPython.noop),
    ]
