# Generated by Django 4.2.30 on 2026-05-17 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_fanew_seed_gateway_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanewsection',
            name='decorative_animation_enabled',
            field=models.BooleanField(default=True, verbose_name='فعال\u200cسازی حرکت آهسته گل\u200cها'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='decorative_blur_intensity',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='میزان blur لبه\u200cها'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='decorative_flowers_enabled',
            field=models.BooleanField(default=False, help_text='لایه تزئینی بین Hero و Gateway. فقط برای حس بصری لوکس؛ محتوایی نیست.', verbose_name='فعال\u200cسازی لایه تزئینی گل\u200cها'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='decorative_left_image',
            field=models.ImageField(blank=True, help_text='ترجیحاً WebP شفاف با شاخه گل کاغذی صورتی.', null=True, upload_to='fa-new/decorative/', verbose_name='تصویر گل سمت چپ'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='decorative_opacity',
            field=models.PositiveIntegerField(default=65, help_text='برای حس سینمایی subtle معمولاً بازه ۵۵ تا ۷۵ مناسب است.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='شفافیت لایه گل (%)'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='decorative_right_image',
            field=models.ImageField(blank=True, help_text='نسخه سبک\u200cتر سمت راست. ترجیحاً WebP شفاف.', null=True, upload_to='fa-new/decorative/', verbose_name='تصویر گل سمت راست'),
        ),
        migrations.AddField(
            model_name='fanewsection',
            name='decorative_show_on_mobile',
            field=models.BooleanField(default=False, help_text='اگر خاموش باشد، در موبایل لایه تزئینی کامل مخفی می\u200cشود.', verbose_name='نمایش تزئینات در موبایل'),
        ),
    ]
