# Generated by Django 4.2.29 on 2026-05-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_fanew_decorative_transition_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fafootersettings',
            name='logo_max_width',
            field=models.PositiveIntegerField(default=120, help_text='حداکثر عرض لوگو در فوتر به پیکسل. پیش\u200cفرض: ۱۲۰', verbose_name='عرض لوگو (px)'),
        ),
    ]
