# Generated by Django 4.2.30 on 2026-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_fanewsection_and_item_extend'),
    ]

    operations = [
        migrations.AddField(
            model_name='fafootersettings',
            name='athens_address',
            field=models.CharField(blank=True, default='آتن، آلیموس، خیابان پوزیدوناس، شماره ۷۸', max_length=300, verbose_name='نشانی دفتر آتن'),
        ),
        migrations.AddField(
            model_name='fafootersettings',
            name='athens_phone',
            field=models.CharField(blank=True, default='+30 698 598 9596', max_length=120, verbose_name='تلفن دفتر آتن'),
        ),
        migrations.AddField(
            model_name='fafootersettings',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='لینک فیسبوک'),
        ),
        migrations.AddField(
            model_name='fafootersettings',
            name='tehran_address',
            field=models.CharField(blank=True, help_text='نشانی کامل دفتر تهران.', max_length=300, verbose_name='نشانی دفتر تهران'),
        ),
        migrations.AddField(
            model_name='fafootersettings',
            name='tehran_phone',
            field=models.CharField(blank=True, help_text='می\u200cتوانید چند شماره را با «/» از هم جدا کنید.', max_length=120, verbose_name='تلفن دفتر تهران'),
        ),
        migrations.AddField(
            model_name='fafootersettings',
            name='x_url',
            field=models.CharField(blank=True, help_text='مثال: https://x.com/adonisgroup', max_length=300, verbose_name='لینک ایکس (توییتر)'),
        ),
        migrations.AddField(
            model_name='fafootersettings',
            name='youtube_url',
            field=models.CharField(blank=True, help_text='مثال: https://youtube.com/@adonisgroup', max_length=300, verbose_name='لینک یوتیوب'),
        ),
        migrations.AlterField(
            model_name='fanewsection',
            name='section_type',
            field=models.CharField(choices=[('why_greece', 'مزایای کلیدی یونان'), ('why_adonis', 'آشنایی با آدونیس'), ('intro_stats', 'آشنایی با آدونیس (قدیمی)'), ('services', 'خدمات آدونیس'), ('routes', 'مسیرهای گلدن ویزا'), ('projects', 'پروژه\u200cهای منتخب'), ('process', 'فرآیند همکاری'), ('trust', 'اعتماد و تجربه'), ('consult', 'مشاوره رایگان'), ('gateway', 'معرفی خدمات آدونیس')], max_length=20, verbose_name='نوع بخش'),
        ),
    ]
