# Generated by Django 4.2.30 on 2026-05-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_alter_fanewsection_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanewsection',
            name='section_type',
            field=models.CharField(choices=[('why_greece', 'مزایای کلیدی یونان'), ('why_adonis', 'آشنایی با آدونیس'), ('intro_stats', 'آشنایی با آدونیس (قدیمی)'), ('services', 'خدمات آدونیس'), ('routes', 'مسیرهای گلدن ویزا'), ('projects', 'پروژه\u200cهای منتخب'), ('process', 'فرآیند همکاری'), ('trust', 'اعتماد و تجربه'), ('consult', 'مشاوره رایگان'), ('gateway', 'معرفی خدمات آدونیس'), ('residency_types', 'انواع اقامت یونان (۳ کارت لاکچری)'), ('featured_properties', 'پروژه\u200cهای منتخب املاک (کاروسل)')], max_length=20, verbose_name='نوع بخش'),
        ),
    ]
