# Generated by Django 4.2.30 on 2026-05-31 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_add_english_content_pipeline'),
        ('core', '0107_alter_fanewsection_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanewsectionitem',
            name='image',
            field=models.ImageField(blank=True, help_text='برای پروژه\u200cها و کارت\u200cهای اقامت (مسیرها/انواع اقامت)', null=True, upload_to='fa-new/sections/', verbose_name='تصویر'),
        ),
        migrations.CreateModel(
            name='FaNewFeaturedProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_1', models.ForeignKey(blank=True, help_text='اولین ملک در کاروسل صفحه اصلی فارسی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_1', to='properties.property', verbose_name='ملک منتخب ۱')),
                ('property_2', models.ForeignKey(blank=True, help_text='دومین ملک در کاروسل صفحه اصلی فارسی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_2', to='properties.property', verbose_name='ملک منتخب ۲')),
                ('property_3', models.ForeignKey(blank=True, help_text='سومین ملک در کاروسل صفحه اصلی فارسی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_3', to='properties.property', verbose_name='ملک منتخب ۳')),
                ('property_4', models.ForeignKey(blank=True, help_text='چهارمین ملک در کاروسل صفحه اصلی فارسی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_4', to='properties.property', verbose_name='ملک منتخب ۴')),
                ('property_5', models.ForeignKey(blank=True, help_text='پنجمین ملک در کاروسل صفحه اصلی فارسی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_5', to='properties.property', verbose_name='ملک منتخب ۵')),
            ],
            options={
                'verbose_name': 'املاک منتخب کاروسل',
                'verbose_name_plural': 'املاک منتخب کاروسل',
            },
        ),
    ]
