# Generated by Django 4.2.30 on 2026-05-31 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persian_cms', '0004_add_fa_property'),
        ('core', '0108_add_fanewfeaturedproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanewfeaturedproperties',
            name='property_1',
            field=models.ForeignKey(blank=True, help_text='اولین ملک در کاروسل صفحه اصلی فارسی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_1', to='persian_cms.faproperty', verbose_name='ملک منتخب ۱'),
        ),
        migrations.AlterField(
            model_name='fanewfeaturedproperties',
            name='property_2',
            field=models.ForeignKey(blank=True, help_text='دومین ملک در کاروسل صفحه اصلی فارسی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_2', to='persian_cms.faproperty', verbose_name='ملک منتخب ۲'),
        ),
        migrations.AlterField(
            model_name='fanewfeaturedproperties',
            name='property_3',
            field=models.ForeignKey(blank=True, help_text='سومین ملک در کاروسل صفحه اصلی فارسی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_3', to='persian_cms.faproperty', verbose_name='ملک منتخب ۳'),
        ),
        migrations.AlterField(
            model_name='fanewfeaturedproperties',
            name='property_4',
            field=models.ForeignKey(blank=True, help_text='چهارمین ملک در کاروسل صفحه اصلی فارسی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_4', to='persian_cms.faproperty', verbose_name='ملک منتخب ۴'),
        ),
        migrations.AlterField(
            model_name='fanewfeaturedproperties',
            name='property_5',
            field=models.ForeignKey(blank=True, help_text='پنجمین ملک در کاروسل صفحه اصلی فارسی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_slot_5', to='persian_cms.faproperty', verbose_name='ملک منتخب ۵'),
        ),
    ]
