# Generated by Django 4.2.30 on 2026-05-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_update_fanewfeaturedproperties_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanavmenuitem',
            name='url',
            field=models.CharField(blank=True, default='', help_text='برای منوی اصلی با زیرمنو خالی بگذارید. برای زیرمنو آدرس صفحه را وارد کنید.', max_length=500, verbose_name='لینک'),
        ),
    ]
