# Generated by Django 4.2.30 on 2026-06-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_add_why_adonis_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanewsection',
            name='title_color',
            field=models.CharField(blank=True, default='#0B1F3A', help_text='رنگ عنوان اصلی سکشن (مثال: #0B1F3A برای سرمه\u200cای)', max_length=30, verbose_name='رنگ عنوان'),
        ),
    ]
