# Generated by Django 4.2.30 on 2026-06-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_add_title_color_to_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanewsection',
            name='subtitle_alignment',
            field=models.CharField(choices=[('right', 'right'), ('center', 'center'), ('left', 'left'), ('justify', 'justify')], default='center', max_length=10, verbose_name='تراز زیرعنوان'),
        ),
        migrations.AlterField(
            model_name='fanewsection',
            name='text_alignment',
            field=models.CharField(choices=[('right', 'right'), ('center', 'center'), ('left', 'left'), ('justify', 'justify')], default='center', max_length=10, verbose_name='تراز عنوان'),
        ),
    ]
