# Generated by Django 4.2.28 on 2026-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Auto-generated from title. Used in URL: /brochure/<slug>/', max_length=200, unique=True, verbose_name='URL Slug')),
                ('pdf_file', models.FileField(help_text='Upload the brochure PDF. Pages will be auto-converted to images.', upload_to='brochures/pdf/', verbose_name='PDF File')),
                ('cover_image', models.ImageField(blank=True, help_text='Optional. Auto-generated from page 1 if left blank.', null=True, upload_to='brochures/covers/', verbose_name='Cover Image')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='Page Count')),
                ('page_width', models.PositiveIntegerField(default=0, verbose_name='Page Width (px)')),
                ('page_height', models.PositiveIntegerField(default=0, verbose_name='Page Height (px)')),
                ('conversion_status', models.CharField(choices=[('pending', 'Pending Conversion'), ('processing', 'Processing…'), ('ready', 'Ready'), ('failed', 'Conversion Failed')], default='pending', max_length=20, verbose_name='Conversion Status')),
                ('conversion_error', models.TextField(blank=True, verbose_name='Conversion Error Log')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brochure',
                'verbose_name_plural': 'Brochures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='brochures_b_slug_5a9a2c_idx'), models.Index(fields=['is_published', 'conversion_status'], name='brochures_b_is_publ_d52c1b_idx')],
            },
        ),
    ]
