# Generated by Django 4.2.28 on 2026-03-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochure',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='cover_image_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cover Image ALT Text'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=120, verbose_name='Focus Keyword'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='OG Image'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='robots_follow',
            field=models.BooleanField(default=True, verbose_name='Follow links'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='robots_index',
            field=models.BooleanField(default=True, verbose_name='Allow indexing'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='seo_allow_publish_override',
            field=models.BooleanField(default=False, verbose_name='Override SEO check'),
        ),
        migrations.AddField(
            model_name='brochure',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='SEO Title'),
        ),
    ]
