# Generated by Django 6.0.1 on 2026-02-01 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_label', models.CharField(help_text='e.g., €250K Plan', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Property Category',
                'verbose_name_plural': 'Property Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(help_text='Short description shown in card', max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_label', models.CharField(help_text='e.g., €250K Plan', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('area', models.CharField(help_text='e.g., South Athens, Alimos', max_length=100)),
                ('floors', models.PositiveIntegerField(default=1)),
                ('units', models.PositiveIntegerField(default=1, help_text='Number of units')),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('size_sqm', models.PositiveIntegerField(blank=True, help_text='Size in square meters', null=True)),
                ('feature_1', models.CharField(blank=True, help_text='e.g., 🌅 Fully Renovated', max_length=100)),
                ('feature_2', models.CharField(blank=True, help_text='e.g., 🏢 4 Floors', max_length=100)),
                ('feature_3', models.CharField(blank=True, help_text='e.g., 🛂 Delivery May 2026', max_length=100)),
                ('feature_4', models.CharField(blank=True, help_text='e.g., 🏡 Premium Quality', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out'), ('coming_soon', 'Coming Soon'), ('pre_sale', 'Pre-Sale')], default='available', max_length=20)),
                ('delivery_date', models.CharField(blank=True, help_text='e.g., May 2026', max_length=50)),
                ('golden_visa_eligible', models.BooleanField(default=True)),
                ('golden_visa_amount', models.CharField(default='250K', help_text='e.g., 250K or 800K', max_length=20)),
                ('main_image', models.ImageField(blank=True, upload_to='properties/')),
                ('image_2', models.ImageField(blank=True, upload_to='properties/')),
                ('image_3', models.ImageField(blank=True, upload_to='properties/')),
                ('image_4', models.ImageField(blank=True, upload_to='properties/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('whatsapp_message', models.CharField(blank=True, help_text='Custom WhatsApp message', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.propertycategory')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['order'],
            },
        ),
    ]
