# Generated by Django 6.0.2 on 2026-02-06 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_10',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 10'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 5'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 6'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_7',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 7'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_8',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 8'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_9',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 9'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Primary image shown in property cards. Recommended: 1200x800px', upload_to='properties/', verbose_name='Main Image (cover)'),
        ),
        migrations.CreateModel(
            name='PropertyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Interest Request',
                'verbose_name_plural': 'Property Interest Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
