# Generated by Django 6.0.2 on 2026-02-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_image_10_property_image_5_property_image_6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='timeline_stage',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('starting', 'Starting Renovation'), ('in_progress', 'Renovation In Progress'), ('finishing', 'Finishing Soon'), ('delivery', 'Ready for Delivery')], default='not_started', help_text='Current stage of construction/renovation', max_length=20, verbose_name='Construction Timeline'),
        ),
    ]
