# Generated by Django 6.0.2 on 2026-02-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_timeline_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='timeline_stage',
            field=models.CharField(choices=[('coming_soon', 'Coming Soon'), ('started', 'Renovation Started'), ('in_progress', 'Renovation In Progress'), ('finished', 'Renovation Finished'), ('ready', 'Ready to Deliver')], default='coming_soon', help_text='Current stage of construction/renovation', max_length=20, verbose_name='Project Status'),
        ),
    ]
