# Generated by Django 6.0.2 on 2026-02-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_timeline_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Still Available'), ('sold_out_soon', 'Sold Out Soon'), ('sold_out', 'Sold Out')], default='available', max_length=20),
        ),
    ]
