# Generated by Django 6.0.2 on 2026-02-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='golden_visa_amount',
        ),
        migrations.AddField(
            model_name='property',
            name='price_tier',
            field=models.CharField(choices=[('250', '€250K'), ('400', '€400K'), ('800', '€800K')], default='250', help_text='Select the Golden Visa price category for this property', max_length=10, verbose_name='Price Tier (Golden Visa)'),
        ),
    ]
