# Generated by Django 6.0.2 on 2026-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_property_golden_visa_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_tier',
            field=models.CharField(choices=[('400', '€400K'), ('800', '€800K')], default='400', help_text='Select the Golden Visa price category for this property', max_length=10, verbose_name='Price Tier (Golden Visa)'),
        ),
    ]
