# Generated by Django 6.0.1 on 2026-02-15 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_price_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_label', models.CharField(help_text='e.g., Unit A1, Floor 2 - Apt 3', max_length=100, verbose_name='Unit Label')),
                ('size_sqm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Size (m²)')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Bathrooms')),
                ('parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (€)')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20, verbose_name='Status')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Row Order')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_units', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Unit',
                'verbose_name_plural': 'Property Units',
                'ordering': ['order', 'unit_label'],
            },
        ),
        migrations.CreateModel(
            name='UnitBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.propertyunit')),
            ],
            options={
                'verbose_name': 'Unit Booking Request',
                'verbose_name_plural': 'Unit Booking Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
