# Generated by Django 6.0.1 on 2026-02-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertyunit_unitbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='timeline_stage',
            field=models.CharField(choices=[('ready_to_start', 'Ready to Start Renovation'), ('under_renovation', 'Under Renovation'), ('finishing_soon', 'Renovation Will Be Finished Soon'), ('ready', 'Ready to Deliver')], default='coming_soon', help_text='Current stage of construction/renovation', max_length=20, verbose_name='Project Status'),
        ),
    ]
