# Generated by Django 6.0.1 on 2026-02-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_property_timeline_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_11',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 11'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_12',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 12'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_13',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 13'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_14',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 14'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_15',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 15'),
        ),
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video for this property (MP4 recommended, max 100MB)', upload_to='properties/videos/', verbose_name='Property Video'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_poster',
            field=models.ImageField(blank=True, help_text='Thumbnail image shown before video plays', upload_to='properties/', verbose_name='Video Poster'),
        ),
    ]
