# Generated by Django 6.0.1 on 2026-02-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_image_11_property_image_12_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['display_order', '-is_featured', '-created_at'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (0 = top)', verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_special_offer',
            field=models.BooleanField(default=False, help_text='Mark as a special sale/promotion', verbose_name='Special Offer'),
        ),
        migrations.AddField(
            model_name='property',
            name='show_on_homepage',
            field=models.BooleanField(default=True, help_text='Display this property on the front page', verbose_name='Show on Homepage'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from website', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Highlight as a featured/special property', verbose_name='Featured Property'),
        ),
        migrations.AlterField(
            model_name='propertyunit',
            name='parking',
            field=models.BooleanField(default=True, verbose_name='Parking'),
        ),
    ]
