# Generated by Django 6.0.1 on 2026-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_property_options_property_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_highlight_1',
            field=models.CharField(blank=True, help_text='e.g., Sandy beaches nearby', max_length=100, verbose_name='Area Highlight 1'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_2',
            field=models.CharField(blank=True, help_text='e.g., Restaurants & cafes', max_length=100, verbose_name='Area Highlight 2'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_3',
            field=models.CharField(blank=True, help_text='e.g., Shopping centers', max_length=100, verbose_name='Area Highlight 3'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_4',
            field=models.CharField(blank=True, help_text='e.g., International schools', max_length=100, verbose_name='Area Highlight 4'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_5',
            field=models.CharField(blank=True, help_text='e.g., Parks & green spaces', max_length=100, verbose_name='Area Highlight 5'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_6',
            field=models.CharField(blank=True, help_text='e.g., Medical facilities', max_length=100, verbose_name='Area Highlight 6'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_acropolis',
            field=models.CharField(blank=True, help_text='e.g., 10 km, 20 min by metro', max_length=50, verbose_name='Distance to Acropolis'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_airport',
            field=models.CharField(blank=True, help_text='e.g., 25 km, 30 min by car', max_length=50, verbose_name='Distance to Airport'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_center',
            field=models.CharField(blank=True, help_text='e.g., 8 km, 15 min by car', max_length=50, verbose_name='Distance to Athens Center'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_metro',
            field=models.CharField(blank=True, help_text='e.g., 300m, 4 min walk', max_length=50, verbose_name='Distance to Metro Station'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_sea',
            field=models.CharField(blank=True, help_text='e.g., 500m, 2 min walk', max_length=50, verbose_name='Distance to Sea/Beach'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_metro_station',
            field=models.CharField(blank=True, help_text='e.g., Alimos Metro Station', max_length=100, verbose_name='Nearest Metro Station'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_description',
            field=models.TextField(blank=True, help_text='Describe the area, lifestyle, and attractions', verbose_name='Neighborhood Description'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_image',
            field=models.ImageField(blank=True, help_text='Image of the area/beach/neighborhood (recommended: 800x500px)', upload_to='properties/neighborhood/', verbose_name='Neighborhood Image'),
        ),
    ]
