# Generated by Django 6.0.1 on 2026-02-20 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_add_neighborhood_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyinterest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyunit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='unitbooking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyinterest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interests', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertyunit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_units', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='unitbooking',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='properties.propertyunit'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['deleted_at', 'is_active'], name='properties__deleted_093668_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', 'status', 'price_tier'], name='properties__is_acti_faf97f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['display_order', 'is_featured'], name='properties__display_33fefb_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinterest',
            index=models.Index(fields=['deleted_at', 'created_at'], name='properties__deleted_6d509f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinterest',
            index=models.Index(fields=['is_read', 'created_at'], name='properties__is_read_9e1391_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyunit',
            index=models.Index(fields=['property', 'availability', 'deleted_at'], name='properties__propert_7bbf3d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyunit',
            index=models.Index(fields=['deleted_at', 'order'], name='properties__deleted_982ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='unitbooking',
            index=models.Index(fields=['unit', 'created_at'], name='properties__unit_id_16d9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='unitbooking',
            index=models.Index(fields=['is_read', 'created_at'], name='properties__is_read_f8349a_idx'),
        ),
        migrations.AddIndex(
            model_name='unitbooking',
            index=models.Index(fields=['deleted_at', 'created_at'], name='properties__deleted_153430_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyunit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('property', 'unit_label'), name='uniq_active_unit_label_per_property'),
        ),
    ]
