# Generated by Django 4.2.28 on 2026-02-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_property_deleted_at_propertyinterest_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_16',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 16'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_17',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 17'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_18',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 18'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_19',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 19'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_20',
            field=models.ImageField(blank=True, upload_to='properties/', verbose_name='Image 20'),
        ),
        migrations.AlterField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video for this property (MP4 recommended, max 500MB)', upload_to='properties/videos/', verbose_name='Property Video'),
        ),
        migrations.AlterField(
            model_name='property',
            name='video_poster',
            field=models.ImageField(blank=True, help_text='Thumbnail image shown before video plays', upload_to='properties/', verbose_name='Video Poster/Thumbnail'),
        ),
    ]
