# Generated by Django 4.2.28 on 2026-02-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_remove_legacy_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_highlight_1_en',
            field=models.CharField(blank=True, help_text='e.g., Sandy beaches nearby', max_length=100, null=True, verbose_name='Area Highlight 1'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_1_tr',
            field=models.CharField(blank=True, help_text='e.g., Sandy beaches nearby', max_length=100, null=True, verbose_name='Area Highlight 1'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_2_en',
            field=models.CharField(blank=True, help_text='e.g., Restaurants & cafes', max_length=100, null=True, verbose_name='Area Highlight 2'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_2_tr',
            field=models.CharField(blank=True, help_text='e.g., Restaurants & cafes', max_length=100, null=True, verbose_name='Area Highlight 2'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_3_en',
            field=models.CharField(blank=True, help_text='e.g., Shopping centers', max_length=100, null=True, verbose_name='Area Highlight 3'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_3_tr',
            field=models.CharField(blank=True, help_text='e.g., Shopping centers', max_length=100, null=True, verbose_name='Area Highlight 3'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_4_en',
            field=models.CharField(blank=True, help_text='e.g., International schools', max_length=100, null=True, verbose_name='Area Highlight 4'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_4_tr',
            field=models.CharField(blank=True, help_text='e.g., International schools', max_length=100, null=True, verbose_name='Area Highlight 4'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_5_en',
            field=models.CharField(blank=True, help_text='e.g., Parks & green spaces', max_length=100, null=True, verbose_name='Area Highlight 5'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_5_tr',
            field=models.CharField(blank=True, help_text='e.g., Parks & green spaces', max_length=100, null=True, verbose_name='Area Highlight 5'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_6_en',
            field=models.CharField(blank=True, help_text='e.g., Medical facilities', max_length=100, null=True, verbose_name='Area Highlight 6'),
        ),
        migrations.AddField(
            model_name='property',
            name='area_highlight_6_tr',
            field=models.CharField(blank=True, help_text='e.g., Medical facilities', max_length=100, null=True, verbose_name='Area Highlight 6'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='feature_1_en',
            field=models.CharField(blank=True, help_text='e.g., 🌅 Fully Renovated', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='feature_1_tr',
            field=models.CharField(blank=True, help_text='e.g., 🌅 Fully Renovated', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='feature_2_en',
            field=models.CharField(blank=True, help_text='e.g., 🏢 4 Floors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='feature_2_tr',
            field=models.CharField(blank=True, help_text='e.g., 🏢 4 Floors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='feature_3_en',
            field=models.CharField(blank=True, help_text='e.g., 🛂 Delivery May 2026', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='feature_3_tr',
            field=models.CharField(blank=True, help_text='e.g., 🛂 Delivery May 2026', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='feature_4_en',
            field=models.CharField(blank=True, help_text='e.g., 🏡 Premium Quality', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='feature_4_tr',
            field=models.CharField(blank=True, help_text='e.g., 🏡 Premium Quality', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='location_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_description_en',
            field=models.TextField(blank=True, help_text='Describe the area, lifestyle, and attractions', null=True, verbose_name='Neighborhood Description'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_description_tr',
            field=models.TextField(blank=True, help_text='Describe the area, lifestyle, and attractions', null=True, verbose_name='Neighborhood Description'),
        ),
        migrations.AddField(
            model_name='property',
            name='slug_en',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='slug_tr',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tagline_en',
            field=models.CharField(help_text='Short description shown in card', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='tagline_tr',
            field=models.CharField(help_text='Short description shown in card', max_length=200, null=True),
        ),
    ]
