# Generated by Django 4.2.28 on 2026-03-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_amenity_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_private',
            field=models.TextField(blank=True, help_text='Full street address — never shown to the public. Used for geocoding only.', verbose_name='Exact Address (Private)'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, help_text='e.g., Athens', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='property',
            name='lat_private',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Auto-filled by geocoding. Do not edit manually.', max_digits=9, null=True, verbose_name='Latitude (private)'),
        ),
        migrations.AddField(
            model_name='property',
            name='lat_public',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Deliberately shifted from the real location. Auto-generated.', max_digits=9, null=True, verbose_name='Latitude (public, approximate)'),
        ),
        migrations.AddField(
            model_name='property',
            name='lng_private',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Auto-filled by geocoding. Do not edit manually.', max_digits=9, null=True, verbose_name='Longitude (private)'),
        ),
        migrations.AddField(
            model_name='property',
            name='lng_public',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Deliberately shifted from the real location. Auto-generated.', max_digits=9, null=True, verbose_name='Longitude (public, approximate)'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_privacy_mode',
            field=models.CharField(choices=[('circle_only', 'Circle only (no area name)'), ('circle_plus_area', 'Circle + area name')], default='circle_plus_area', max_length=20, verbose_name='Map Privacy Mode'),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='property',
            name='public_radius_m',
            field=models.PositiveIntegerField(default=400, help_text='Radius of the "approximate area" circle shown on the map. 250–800 m recommended.', verbose_name='Public Circle Radius (m)'),
        ),
    ]
