# Generated by Django 4.2.28 on 2026-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_location_map_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Auto-filled by Google Places autocomplete. Used for server-side geocoding.', max_length=500, verbose_name='Google Place ID (Private)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address_private',
            field=models.TextField(blank=True, help_text='Auto-filled by Google Places autocomplete — never shown to the public.', verbose_name='Exact Address (Private)'),
        ),
    ]
