# Generated by Django 4.2.28 on 2026-03-05 11:31

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_add_google_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymedia',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption / Alt text'),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='caption_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption / Alt text'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo. HEIC/iPhone photos are automatically converted to JPEG.', upload_to=properties.models._property_image_upload_path, verbose_name='Photo'),
        ),
    ]
