# Generated by Django 4.2.28 on 2026-03-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_caption_translation_and_seo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Leave blank — canonical is set automatically from the page URL.', verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='property',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword this property page targets (e.g. "athens golden visa apartment"). Used for SEO analysis.', max_length=120, verbose_name='Focus Keyword'),
        ),
        migrations.AddField(
            model_name='property',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Summary shown under the Google result title (max 160 chars). Leave blank to use description excerpt.', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='property',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Custom image for social sharing (1200×630 px). Leave blank to use cover photo.', null=True, upload_to='seo/og/', verbose_name='OG / Social Image'),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Title shown in Google results (max 70 chars). Leave blank to use property name.', max_length=70, verbose_name='SEO Title'),
        ),
    ]
