# Generated by Django 4.2.28 on 2026-03-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_seo_fields_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='robots_follow',
            field=models.BooleanField(default=True, verbose_name='Follow links'),
        ),
        migrations.AddField(
            model_name='property',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Uncheck to add noindex.', verbose_name='Allow indexing'),
        ),
        migrations.AddField(
            model_name='property',
            name='seo_allow_publish_override',
            field=models.BooleanField(default=False, verbose_name='Override SEO check'),
        ),
    ]
