# Generated by Django 4.2.28 on 2026-03-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_property_neighborhood_public_and_area_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, help_text='Optional secondary area shown on the card — e.g. "Alimos" or "Glyfada". Keep it at district or neighbourhood level only; never a street address.', max_length=100, verbose_name='District / Sub-area Label (Public)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, help_text='Public city name shown beside the map circle — e.g. "Athens". Safe to display.', max_length=100, verbose_name='City (Public)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(help_text='Public-facing area description shown on the property card — e.g. "South Athens" or "Piraeus Coast". Do NOT include street numbers or exact addresses here.', max_length=200, verbose_name='Location / Area Label'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location_en',
            field=models.CharField(help_text='Public-facing area description shown on the property card — e.g. "South Athens" or "Piraeus Coast". Do NOT include street numbers or exact addresses here.', max_length=200, null=True, verbose_name='Location / Area Label'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location_tr',
            field=models.CharField(help_text='Public-facing area description shown on the property card — e.g. "South Athens" or "Piraeus Coast". Do NOT include street numbers or exact addresses here.', max_length=200, null=True, verbose_name='Location / Area Label'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood_public_en',
            field=models.CharField(blank=True, help_text='Shown next to the map circle on the property page — e.g. "Piraeus Port" or "Glyfada Coast". Never use a street address here. Leave blank to fall back to the general Area/Location.', max_length=200, null=True, verbose_name='Public Neighborhood Label'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood_public_tr',
            field=models.CharField(blank=True, help_text='Shown next to the map circle on the property page — e.g. "Piraeus Port" or "Glyfada Coast". Never use a street address here. Leave blank to fall back to the general Area/Location.', max_length=200, null=True, verbose_name='Public Neighborhood Label'),
        ),
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Auto-filled from Google Places. NEVER shown on the public website.', max_length=20, verbose_name='Postal Code (Private)'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='caption_en',
            field=models.CharField(blank=True, help_text='Describe what is shown in this image for screen readers and search engines. Example: "Modern living room with sea view, Alimos Athens". Leave blank to fall back to the property name. Tick "Decorative" below if the image is purely visual and needs no description.', max_length=200, null=True, verbose_name='ALT Text'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='caption_tr',
            field=models.CharField(blank=True, help_text='Describe what is shown in this image for screen readers and search engines. Example: "Modern living room with sea view, Alimos Athens". Leave blank to fall back to the property name. Tick "Decorative" below if the image is purely visual and needs no description.', max_length=200, null=True, verbose_name='ALT Text'),
        ),
    ]
