# Generated by Django 4.2.28 on 2026-03-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_alter_property_area_alter_property_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_1',
            field=models.FileField(blank=True, help_text='Upload an MP4 video (max 500 MB). Displayed in a player below the photo gallery.', upload_to='properties/videos/', verbose_name='Video 1'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_1_poster',
            field=models.ImageField(blank=True, help_text='Optional thumbnail shown before Video 1 plays (recommended: 1280×720 px).', upload_to='properties/posters/', verbose_name='Video 1 – Poster / Thumbnail'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_2',
            field=models.FileField(blank=True, help_text='Optional second MP4 video (max 500 MB).', upload_to='properties/videos/', verbose_name='Video 2'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_2_poster',
            field=models.ImageField(blank=True, help_text='Optional thumbnail shown before Video 2 plays.', upload_to='properties/posters/', verbose_name='Video 2 – Poster / Thumbnail'),
        ),
    ]
