# Generated by Django 4.2.28 on 2026-03-13 10:12

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_property_video_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_1',
            field=models.ImageField(blank=True, help_text='iPhone HEIC photos are automatically converted to JPEG.', upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 1'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_10',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 10'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_11',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 11'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_12',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 12'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_13',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 13'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_14',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 14'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_15',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 15'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_2',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 2'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_3',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 3'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_4',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 4'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_5',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 5'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_6',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 6'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_7',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 7'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_8',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 8'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_9',
            field=models.ImageField(blank=True, upload_to=properties.models._property_direct_image_upload_path, verbose_name='Photo 9'),
        ),
    ]
