# Generated by Django 4.2.29 on 2026-04-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_property_direct_image_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name_fa',
            field=models.CharField(blank=True, help_text='Persian name shown on FA landing page cards', max_length=200, verbose_name='نام فارسی'),
        ),
        migrations.AddField(
            model_name='property',
            name='tagline_fa',
            field=models.CharField(blank=True, help_text='Persian tagline shown on FA landing page cards', max_length=300, verbose_name='توضیح کوتاه فارسی'),
        ),
    ]
