# Generated by Django 4.2.28 on 2026-05-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_property_cover_image_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('posts_per_week', models.IntegerField(default=3, verbose_name='پست در هفته')),
                ('base_topics', models.TextField(default='اقامت یونان,گلدن ویزا,خرید ملک یونان,مهاجرت به یونان', help_text='هر موضوع را با کاما جدا کنید', verbose_name='موضوعات پایه')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اجرا')),
            ],
            options={
                'verbose_name': 'برنامه تولید محتوا',
                'verbose_name_plural': 'برنامه\u200cهای تولید محتوا',
            },
        ),
        migrations.CreateModel(
            name='FaContentPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300, verbose_name='کلیدواژه اصلی')),
                ('focus_keywords', models.TextField(blank=True, verbose_name='کلیدواژه\u200cهای تمرکز')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('generating', 'در حال تولید'), ('review', 'بررسی'), ('published', 'منتشر شده'), ('failed', 'خطا')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=400, null=True, unique=True, verbose_name='اسلاگ')),
                ('content', models.TextField(blank=True, verbose_name='محتوا')),
                ('excerpt', models.TextField(blank=True, verbose_name='چکیده')),
                ('meta_title', models.CharField(blank=True, max_length=120, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='توضیحات متا')),
                ('cover_image_url', models.URLField(blank=True, max_length=1000, verbose_name='آدرس تصویر')),
                ('cover_image_thumb', models.URLField(blank=True, max_length=1000, verbose_name='آدرس تامبنیل')),
                ('cover_image_credit', models.CharField(blank=True, max_length=300, verbose_name='کردیت تصویر')),
                ('unsplash_photo_id', models.CharField(blank=True, max_length=50, verbose_name='شناسه Unsplash')),
                ('scheduled_publish', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار برنامه\u200cریزی\u200cشده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('ai_generated', models.BooleanField(default=True, verbose_name='تولید شده با AI')),
                ('error_log', models.TextField(blank=True, verbose_name='لاگ خطا')),
                ('views', models.IntegerField(default=0, verbose_name='بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروز شده در')),
            ],
            options={
                'verbose_name': 'محتوای SEO فارسی',
                'verbose_name_plural': 'محتوای SEO فارسی',
                'ordering': ['-created_at'],
            },
        ),
    ]
