# Generated by Django 4.2.29 on 2026-05-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_add_content_pipeline'),
    ]

    operations = [
    ]
