# Generated by Django 4.2.29 on 2026-05-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_merge_0033_add_content_pipeline_0033_fapropertyproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnContentPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300, verbose_name='Main Keyword')),
                ('focus_keywords', models.TextField(blank=True, verbose_name='Focus Keywords')),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Turkish')], default='en', max_length=5, verbose_name='Language')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('review', 'Review'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=400, null=True, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('meta_title', models.CharField(blank=True, max_length=120, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='Meta Description')),
                ('cover_image_url', models.URLField(blank=True, max_length=1000, verbose_name='Cover Image URL')),
                ('cover_image_thumb', models.URLField(blank=True, max_length=1000, verbose_name='Thumbnail URL')),
                ('cover_image_credit', models.CharField(blank=True, max_length=300, verbose_name='Image Credit')),
                ('unsplash_photo_id', models.CharField(blank=True, max_length=50, verbose_name='Unsplash Photo ID')),
                ('scheduled_publish', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Publish')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('ai_generated', models.BooleanField(default=True, verbose_name='AI Generated')),
                ('error_log', models.TextField(blank=True, verbose_name='Error Log')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'English SEO Content',
                'verbose_name_plural': 'English SEO Contents',
                'ordering': ['-created_at'],
            },
        ),
    ]
