# Generated by Django 4.2.30 on 2026-05-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persian_cms', '0002_seo_fields_pages_and_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persianblogpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=260, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='persianpage',
            name='route_path',
            field=models.CharField(blank=True, help_text='خودکار از روی اسلاگ ساخته می\u200cشود. برای صفحات سفارشی: /fa-new/p/<اسلاگ>/', max_length=300, unique=True, verbose_name='مسیر عمومی'),
        ),
        migrations.AlterField(
            model_name='persianpage',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='اسلاگ'),
        ),
    ]
