# Generated by Django 4.2.30 on 2026-05-31 12:44

import apps.persian_cms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persian_cms', '0003_alter_persianblogpost_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='نام پروژه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('tagline', models.CharField(blank=True, help_text='توضیح کوتاه که در کارت نمایش داده می\u200cشود', max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کامل')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت (یورو)')),
                ('price_label', models.CharField(blank=True, help_text='مثلاً: €250K Plan', max_length=50, verbose_name='برچسب قیمت')),
                ('price_tier', models.CharField(choices=[('250', '€250K'), ('400', '€400K'), ('800', '€800K')], default='250', max_length=10, verbose_name='تیر قیمتی')),
                ('location', models.CharField(blank=True, help_text='مثلاً: جنوب آتن', max_length=200, verbose_name='منطقه')),
                ('area', models.CharField(blank=True, help_text='مثلاً: آلیموس', max_length=100, verbose_name='ناحیه')),
                ('city', models.CharField(blank=True, default='آتن', max_length=100, verbose_name='شهر')),
                ('floors', models.PositiveIntegerField(default=1, verbose_name='تعداد طبقات')),
                ('units', models.PositiveIntegerField(default=1, verbose_name='تعداد واحد')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='تعداد اتاق خواب')),
                ('size_sqm', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ (متر مربع)')),
                ('feature_1', models.CharField(blank=True, help_text='مثلاً: 🌅 بازسازی کامل', max_length=100, verbose_name='ویژگی ۱')),
                ('feature_2', models.CharField(blank=True, max_length=100, verbose_name='ویژگی ۲')),
                ('feature_3', models.CharField(blank=True, max_length=100, verbose_name='ویژگی ۳')),
                ('feature_4', models.CharField(blank=True, max_length=100, verbose_name='ویژگی ۴')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('sold_out_soon', 'به\u200cزودی تمام می\u200cشود'), ('sold_out', 'تمام شده')], default='available', max_length=20, verbose_name='وضعیت')),
                ('timeline_stage', models.CharField(choices=[('ready_to_start', 'آماده شروع بازسازی'), ('under_renovation', 'در حال بازسازی'), ('finishing_soon', 'به\u200cزودی تحویل'), ('ready', 'آماده تحویل')], default='ready', max_length=20, verbose_name='مرحله ساخت')),
                ('delivery_date', models.CharField(blank=True, help_text='مثلاً: خرداد ۱۴۰۵', max_length=50, verbose_name='تاریخ تحویل')),
                ('golden_visa_eligible', models.BooleanField(default=True, verbose_name='واجد شرایط گلدن ویزا')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='عدد کمتر = نمایش زودتر', verbose_name='ترتیب نمایش')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پروژه ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('cover_image_slot', models.PositiveSmallIntegerField(choices=[(0, 'خودکار — اولین عکس موجود'), (1, 'عکس 1'), (2, 'عکس 2'), (3, 'عکس 3'), (4, 'عکس 4'), (5, 'عکس 5'), (6, 'عکس 6'), (7, 'عکس 7'), (8, 'عکس 8'), (9, 'عکس 9'), (10, 'عکس 10'), (11, 'عکس 11'), (12, 'عکس 12'), (13, 'عکس 13'), (14, 'عکس 14'), (15, 'عکس 15')], default=0, help_text='انتخاب کنید کدام عکس به\u200cعنوان کاور در کارت نمایش داده شود.', verbose_name='عکس کاور (کارت)')),
                ('image_1', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۱')),
                ('image_2', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۲')),
                ('image_3', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۳')),
                ('image_4', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۴')),
                ('image_5', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۵')),
                ('image_6', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۶')),
                ('image_7', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۷')),
                ('image_8', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۸')),
                ('image_9', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۹')),
                ('image_10', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۱۰')),
                ('image_11', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۱۱')),
                ('image_12', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۱۲')),
                ('image_13', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۱۳')),
                ('image_14', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۱۴')),
                ('image_15', models.ImageField(blank=True, upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس ۱۵')),
                ('video_1', models.FileField(blank=True, help_text='فایل MP4 (حداکثر ۵۰۰ مگابایت)', upload_to='persian_cms/properties/videos/', verbose_name='ویدیو ۱')),
                ('video_1_poster', models.ImageField(blank=True, upload_to='persian_cms/properties/posters/', verbose_name='پوستر ویدیو ۱')),
                ('video_2', models.FileField(blank=True, upload_to='persian_cms/properties/videos/', verbose_name='ویدیو ۲')),
                ('video_2_poster', models.ImageField(blank=True, upload_to='persian_cms/properties/posters/', verbose_name='پوستر ویدیو ۲')),
            ],
            options={
                'verbose_name': 'ملک فارسی',
                'verbose_name_plural': 'املاک فارسی',
                'db_table': 'persian_cms_property',
                'ordering': ['display_order', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaPropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='persian_cms/properties/gallery/', verbose_name='عکس')),
                ('video', models.FileField(blank=True, upload_to='persian_cms/properties/videos/', verbose_name='ویدیو')),
                ('poster', models.ImageField(blank=True, upload_to='persian_cms/properties/posters/', verbose_name='پوستر ویدیو')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='توضیح/ALT')),
                ('is_cover', models.BooleanField(default=False, verbose_name='عکس کاور')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='persian_cms.faproperty', verbose_name='ملک')),
            ],
            options={
                'verbose_name': 'رسانه ملک',
                'verbose_name_plural': 'رسانه\u200cهای ملک',
                'db_table': 'persian_cms_property_media',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='faproperty',
            index=models.Index(fields=['is_active', 'display_order'], name='persian_cms_is_acti_64b7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='faproperty',
            index=models.Index(fields=['is_featured', 'display_order'], name='persian_cms_is_feat_093669_idx'),
        ),
    ]
