# Generated by Django 4.2.30 on 2026-05-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persian_cms', '0004_add_fa_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faproperty',
            options={'ordering': ['display_order', '-is_featured', '-created_at'], 'verbose_name': 'پروژه ملکی', 'verbose_name_plural': 'پروژه\u200cهای ملکی'},
        ),
        migrations.RemoveField(
            model_name='faproperty',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='faproperty',
            name='size_sqm',
        ),
        migrations.RemoveField(
            model_name='faproperty',
            name='units',
        ),
        migrations.AddField(
            model_name='faproperty',
            name='address',
            field=models.CharField(blank=True, help_text='آدرس دقیق برای نقشه (اختیاری)', max_length=300, verbose_name='آدرس کامل'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='amenities',
            field=models.TextField(blank=True, help_text='هر امکان در یک خط جدید (مثلاً: استخر\\nسونا\\nباشگاه)', verbose_name='امکانات کامل'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='available_units',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='واحدهای موجود'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1, verbose_name='سرویس بهداشتی'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='bedrooms_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر اتاق خواب'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='bedrooms_min',
            field=models.PositiveIntegerField(default=1, verbose_name='حداقل اتاق خواب'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='فقط در صورت نیاز به آدرس متفاوت', verbose_name='آدرس Canonical'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='distance_to_airport',
            field=models.CharField(blank=True, max_length=50, verbose_name='فاصله تا فرودگاه'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='distance_to_center',
            field=models.CharField(blank=True, max_length=50, verbose_name='فاصله تا مرکز شهر'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='distance_to_sea',
            field=models.CharField(blank=True, help_text='مثلاً: ۵۰۰ متر', max_length=50, verbose_name='فاصله تا دریا'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='کلمه کلیدی هدف برای سئو', max_length=100, verbose_name='کلمه کلیدی اصلی'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='headline',
            field=models.CharField(blank=True, help_text='عنوان H1 صفحه جزئیات ملک — اگر خالی باشد، از نام پروژه استفاده می\u200cشود', max_length=400, verbose_name='تیتر اصلی صفحه'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_10_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۱۰'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_10_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۱۰'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_11_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۱۱'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_11_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۱۱'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_12_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۱۲'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_12_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۱۲'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_13_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۱۳'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_13_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۱۳'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_14_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۱۴'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_14_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۱۴'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_15_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۱۵'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_15_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۱۵'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_1_alt',
            field=models.CharField(blank=True, help_text='توضیح عکس برای سئو و دسترس\u200cپذیری', max_length=200, verbose_name='Alt عکس ۱'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_1_caption',
            field=models.CharField(blank=True, help_text='توضیح زیر عکس در گالری', max_length=300, verbose_name='کپشن عکس ۱'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_2_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۲'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_2_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۲'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_3_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۳'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_3_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۳'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_4_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۴'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_4_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۴'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_5_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۵'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_5_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۵'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_6_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۶'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_6_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۶'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_7_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۷'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_7_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۷'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_8_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۸'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_8_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۸'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_9_alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt عکس ۹'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='image_9_caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='کپشن عکس ۹'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='investment_highlights',
            field=models.TextField(blank=True, help_text='هر مزیت در یک خط جدید', verbose_name='مزایای سرمایه\u200cگذاری'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='is_new',
            field=models.BooleanField(default=False, help_text='نمایش برچسب «جدید»', verbose_name='پروژه جدید'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='map_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='map_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='meta_description',
            field=models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر — توضیح کوتاه برای نمایش در نتایج گوگل', max_length=160, verbose_name='توضیح سئو (Meta Description)'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='meta_title',
            field=models.CharField(blank=True, help_text='حداکثر ۷۰ کاراکتر — اگر خالی باشد از نام پروژه استفاده می\u200cشود', max_length=70, verbose_name='عنوان سئو (Meta Title)'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='noindex',
            field=models.BooleanField(default=False, verbose_name='جلوگیری از ایندکس (noindex)'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='og_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='توضیح شبکه اجتماعی (OG Description)'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='og_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان شبکه اجتماعی (OG Title)'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='parking_spaces',
            field=models.PositiveIntegerField(default=0, verbose_name='پارکینگ'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='قیمت هر متر مربع (یورو)'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('penthouse', 'پنت\u200cهاوس'), ('duplex', 'دوبلکس'), ('townhouse', 'تاون\u200cهاوس'), ('commercial', 'تجاری'), ('land', 'زمین')], default='apartment', max_length=20, verbose_name='نوع ملک'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='rental_yield',
            field=models.CharField(blank=True, help_text='مثلاً: ۵-۷٪ سالانه', max_length=50, verbose_name='بازده اجاره'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='schema_markup',
            field=models.TextField(blank=True, help_text='کد JSON-LD سفارشی برای Rich Snippets', verbose_name='Schema Markup (JSON-LD)'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='short_description',
            field=models.TextField(blank=True, help_text='خلاصه ۲-۳ جمله\u200cای برای نمایش در کارت و پیش\u200cنمایش', max_length=500, verbose_name='خلاصه توضیحات'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='size_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر متراژ (m²)'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='size_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل متراژ (m²)'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='total_units',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد کل واحدها'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='video_1_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان ویدیو ۱'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='video_2_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان ویدیو ۲'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='virtual_tour_url',
            field=models.URLField(blank=True, help_text='آدرس تور ۳۶۰ درجه (اختیاری)', verbose_name='لینک تور مجازی'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سال ساخت'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='آدرس ویدیو یوتیوب (اختیاری)', verbose_name='لینک یوتیوب'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='area',
            field=models.CharField(blank=True, help_text='مثلاً: گلیفادا، آلیموس', max_length=100, verbose_name='محله / ناحیه'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='city',
            field=models.CharField(default='آتن', max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='cover_image_slot',
            field=models.PositiveSmallIntegerField(choices=[(0, 'خودکار — اولین عکس موجود'), (1, 'عکس 1'), (2, 'عکس 2'), (3, 'عکس 3'), (4, 'عکس 4'), (5, 'عکس 5'), (6, 'عکس 6'), (7, 'عکس 7'), (8, 'عکس 8'), (9, 'عکس 9'), (10, 'عکس 10'), (11, 'عکس 11'), (12, 'عکس 12'), (13, 'عکس 13'), (14, 'عکس 14'), (15, 'عکس 15')], default=0, help_text='کدام عکس در کارت و اشتراک\u200cگذاری نمایش داده شود', verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='delivery_date',
            field=models.CharField(blank=True, help_text='مثلاً: Q4 2025 یا تابستان ۱۴۰۴', max_length=50, verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات کامل پروژه برای صفحه جزئیات (HTML مجاز)', verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='feature_1',
            field=models.CharField(blank=True, help_text='مثلاً: 🏊 استخر خصوصی', max_length=100, verbose_name='ویژگی برجسته ۱'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='feature_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='ویژگی برجسته ۲'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='feature_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='ویژگی برجسته ۳'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='feature_4',
            field=models.CharField(blank=True, max_length=100, verbose_name='ویژگی برجسته ۴'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='نمایش در بخش ویژه صفحه اصلی', verbose_name='پروژه ویژه'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='name',
            field=models.CharField(help_text='نام رسمی پروژه که در عنوان صفحه نمایش داده می\u200cشود', max_length=200, verbose_name='نام پروژه'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='قیمت شروع به یورو — فقط عدد بدون علامت', max_digits=12, null=True, verbose_name='قیمت شروع (یورو)'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='price_label',
            field=models.CharField(blank=True, help_text='متن نمایشی قیمت (مثلاً: از €۲۵۰,۰۰۰ یا تماس بگیرید)', max_length=80, verbose_name='برچسب قیمت'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='price_tier',
            field=models.CharField(choices=[('250', '€250K Plan'), ('400', '€400K Plan'), ('800', '€800K Plan'), ('custom', 'قیمت سفارشی')], default='250', max_length=10, verbose_name='پلن گلدن ویزا'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='آدرس صفحه: /fa-new/properties/[slug]/', max_length=200, unique=True, verbose_name='اسلاگ URL'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='status',
            field=models.CharField(choices=[('available', 'موجود برای فروش'), ('reserved', 'رزرو شده'), ('sold_out_soon', 'واحدهای محدود'), ('sold_out', 'فروخته شده')], default='available', max_length=20, verbose_name='وضعیت فروش'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='tagline',
            field=models.CharField(blank=True, help_text='یک جمله جذاب که در کارت نمایش داده می\u200cشود (مثلاً: زندگی لوکس در قلب آتن)', max_length=300, verbose_name='شعار / توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='timeline_stage',
            field=models.CharField(choices=[('off_plan', 'پیش\u200cفروش'), ('under_construction', 'در حال ساخت'), ('ready_to_start', 'آماده شروع بازسازی'), ('under_renovation', 'در حال بازسازی'), ('finishing_soon', 'به\u200cزودی تحویل'), ('ready', 'آماده تحویل')], default='ready', max_length=20, verbose_name='مرحله پروژه'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='video_1_poster',
            field=models.ImageField(blank=True, upload_to='persian_cms/properties/posters/', verbose_name='تصویر پوستر ویدیو ۱'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='video_2_poster',
            field=models.ImageField(blank=True, upload_to='persian_cms/properties/posters/', verbose_name='تصویر پوستر ویدیو ۲'),
        ),
        migrations.AddIndex(
            model_name='faproperty',
            index=models.Index(fields=['property_type', 'is_active'], name='persian_cms_propert_68bd05_idx'),
        ),
        migrations.AddIndex(
            model_name='faproperty',
            index=models.Index(fields=['price_tier', 'is_active'], name='persian_cms_price_t_7429f5_idx'),
        ),
    ]
