# Generated by Django 4.2.30 on 2026-05-31 16:27

import apps.persian_cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persian_cms', '0005_enhance_fa_property_luxury'),
    ]

    operations = [
        migrations.AddField(
            model_name='faproperty',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='عکس اصلی که در کارت و اشتراک\u200cگذاری نمایش داده می\u200cشود', upload_to=apps.persian_cms.models._fa_property_image_upload_path, verbose_name='عکس کاور اصلی'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='cover_image_alt',
            field=models.CharField(blank=True, help_text='توضیح عکس برای سئو و دسترس\u200cپذیری', max_length=200, verbose_name='Alt عکس کاور'),
        ),
        migrations.AlterField(
            model_name='faproperty',
            name='cover_image_slot',
            field=models.PositiveSmallIntegerField(choices=[(0, 'خودکار — اولین عکس موجود'), (1, 'عکس 1'), (2, 'عکس 2'), (3, 'عکس 3'), (4, 'عکس 4'), (5, 'عکس 5'), (6, 'عکس 6'), (7, 'عکس 7'), (8, 'عکس 8'), (9, 'عکس 9'), (10, 'عکس 10'), (11, 'عکس 11'), (12, 'عکس 12'), (13, 'عکس 13'), (14, 'عکس 14'), (15, 'عکس 15')], default=0, help_text='کدام عکس در کارت و اشتراک\u200cگذاری نمایش داده شود', verbose_name='انتخاب از گالری'),
        ),
    ]
