# Generated by Django 4.2.30 on 2026-06-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persian_cms', '0006_add_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='persianmenuitem',
            name='target_page',
            field=models.ForeignKey(blank=True, help_text='یک صفحه انتخاب کنید تا لینک به صورت خودکار پر شود', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='persian_cms.persianpage', verbose_name='صفحه هدف'),
        ),
        migrations.AlterField(
            model_name='persianmenuitem',
            name='url',
            field=models.CharField(blank=True, help_text='اگر صفحه هدف انتخاب شده باشد، این فیلد خودکار پر می\u200cشود', max_length=500, verbose_name='لینک'),
        ),
    ]
