# Generated by Django 4.2.30 on 2026-06-01 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persian_cms', '0007_add_target_page_to_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='faproperty',
            name='cta_primary_text',
            field=models.CharField(default='دریافت مشاوره رایگان', max_length=100, verbose_name='متن دکمه اصلی'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='cta_secondary_text',
            field=models.CharField(blank=True, default='رزرو واحد', max_length=100, verbose_name='متن دکمه ثانویه'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='description_section_title',
            field=models.CharField(blank=True, default='معرفی پروژه', max_length=200, verbose_name='عنوان بخش معرفی'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='متن زیر عنوان اصلی در بخش هیرو', max_length=300, verbose_name='زیرعنوان هیرو'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='location_description_fa',
            field=models.TextField(blank=True, help_text='توضیحات درباره محله و منطقه پروژه', verbose_name='توضیح منطقه'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='آدرس iframe گوگل مپ را از Share > Embed کپی کنید', verbose_name='لینک Embed نقشه گوگل'),
        ),
        migrations.AddField(
            model_name='faproperty',
            name='show_golden_visa_badge',
            field=models.BooleanField(default=True, verbose_name='نمایش بج گلدن ویزا'),
        ),
        migrations.AlterField(
            model_name='persianpage',
            name='page_type',
            field=models.CharField(choices=[('home', 'خانه'), ('about', 'درباره ما'), ('blog', 'بلاگ'), ('golden_visa', 'گلدن ویزا'), ('financial_independence', 'تمکن مالی'), ('contact', 'تماس'), ('custom', 'سفارشی')], default='custom', max_length=30, verbose_name='نوع صفحه'),
        ),
        migrations.CreateModel(
            name='FaPropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.CharField(help_text='مثلاً: همکف، ۱، ۲، پنت\u200cهاوس', max_length=50, verbose_name='طبقه')),
                ('unit_number', models.CharField(max_length=50, verbose_name='شماره واحد')),
                ('area_sqm', models.PositiveIntegerField(verbose_name='متراژ (متر مربع)')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='تعداد خواب')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='تعداد حمام')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='بالکن')),
                ('balcony_size', models.CharField(blank=True, max_length=50, verbose_name='متراژ بالکن')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت (یورو)')),
                ('price_label', models.CharField(blank=True, help_text='مثلاً: از €۲۵۰,۰۰۰', max_length=100, verbose_name='برچسب قیمت')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('reserved', 'رزرو شده'), ('sold', 'فروخته شده')], default='available', max_length=20, verbose_name='وضعیت')),
                ('short_note_fa', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('floor_plan_image', models.ImageField(blank=True, upload_to='persian_cms/properties/floor_plans/', verbose_name='پلان واحد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='persian_cms.faproperty', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحدها و قیمت\u200cها',
                'db_table': 'persian_cms_property_unit',
                'ordering': ['order', 'floor', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='FaPropertyQuickInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_fa', models.CharField(max_length=100, verbose_name='عنوان')),
                ('value_fa', models.CharField(max_length=150, verbose_name='مقدار')),
                ('icon', models.CharField(choices=[('fa-euro-sign', 'قیمت'), ('fa-building', 'طبقات'), ('fa-door-open', 'واحدها'), ('fa-ruler-combined', 'متراژ'), ('fa-hourglass-half', 'وضعیت'), ('fa-calendar', 'تحویل'), ('fa-passport', 'گلدن ویزا'), ('fa-location-dot', 'موقعیت'), ('fa-bed', 'اتاق خواب'), ('fa-bath', 'حمام'), ('fa-car', 'پارکینگ'), ('fa-water', 'دریا'), ('fa-chart-line', 'بازده'), ('fa-home', 'نوع ملک')], default='fa-check-circle', max_length=30, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_info_items', to='persian_cms.faproperty', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'اطلاعات سریع',
                'verbose_name_plural': 'اطلاعات سریع پروژه',
                'db_table': 'persian_cms_property_quick_info',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FaPropertyProgressStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان مرحله')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات')),
                ('progress_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت')),
                ('status', models.CharField(choices=[('completed', 'تکمیل شده'), ('in_progress', 'در حال انجام'), ('upcoming', 'در آینده')], default='upcoming', max_length=20, verbose_name='وضعیت')),
                ('date_label_fa', models.CharField(blank=True, help_text='مثلاً: تابستان ۱۴۰۳', max_length=100, verbose_name='تاریخ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_steps', to='persian_cms.faproperty', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'مرحله پیشرفت',
                'verbose_name_plural': 'مراحل پیشرفت پروژه',
                'db_table': 'persian_cms_property_progress_step',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FaPropertyLocationDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_fa', models.CharField(help_text='مثلاً: مرکز شهر آتن', max_length=100, verbose_name='عنوان مکان')),
                ('value_fa', models.CharField(help_text='مثلاً: ۱۵ دقیقه یا ۵۰۰ متر', max_length=50, verbose_name='فاصله')),
                ('icon', models.CharField(choices=[('fa-city', 'مرکز شهر'), ('fa-train-subway', 'مترو'), ('fa-train-tram', 'تراموا'), ('fa-water', 'دریا'), ('fa-plane', 'فرودگاه'), ('fa-shopping-cart', 'مرکز خرید'), ('fa-hospital', 'بیمارستان'), ('fa-school', 'مدرسه'), ('fa-utensils', 'رستوران'), ('fa-tree', 'پارک'), ('fa-bus', 'اتوبوس'), ('fa-car', 'بزرگراه'), ('fa-building', 'مرکز تجاری'), ('fa-mosque', 'مسجد'), ('fa-church', 'کلیسا')], default='fa-building', max_length=30, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_distances', to='persian_cms.faproperty', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'فاصله مکانی',
                'verbose_name_plural': 'فاصله\u200cهای مکانی',
                'db_table': 'persian_cms_property_location_distance',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FaPropertyInvestmentHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(choices=[('fa-chart-line', 'نمودار رشد'), ('fa-coins', 'سکه'), ('fa-hand-holding-dollar', 'سرمایه\u200cگذاری'), ('fa-building', 'ساختمان'), ('fa-location-dot', 'موقعیت'), ('fa-clock', 'زمان'), ('fa-shield-halved', 'امنیت'), ('fa-passport', 'پاسپورت'), ('fa-house', 'خانه'), ('fa-percent', 'درصد'), ('fa-star', 'ستاره'), ('fa-check-circle', 'تیک'), ('fa-award', 'جایزه'), ('fa-gem', 'الماس'), ('fa-globe', 'جهان')], default='fa-check-circle', max_length=30, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_highlights_items', to='persian_cms.faproperty', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'مزیت سرمایه\u200cگذاری',
                'verbose_name_plural': 'مزایای سرمایه\u200cگذاری',
                'db_table': 'persian_cms_property_investment_highlight',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FaPropertyGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='persian_cms/properties/gallery/', verbose_name='تصویر')),
                ('title_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان تصویر')),
                ('tag', models.CharField(choices=[('exterior', 'نمای بیرونی'), ('interior', 'نمای داخلی'), ('lobby', 'لابی'), ('view', 'چشم\u200cانداز'), ('floor_plan', 'پلان طبقات'), ('construction', 'پیشرفت ساخت'), ('amenities', 'امکانات'), ('bedroom', 'اتاق خواب'), ('kitchen', 'آشپزخانه'), ('bathroom', 'سرویس بهداشتی'), ('balcony', 'بالکن'), ('pool', 'استخر'), ('gym', 'باشگاه'), ('parking', 'پارکینگ'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دسته\u200cبندی')),
                ('short_description_fa', models.TextField(blank=True, max_length=500, verbose_name='توضیح کوتاه')),
                ('alt_text', models.CharField(blank=True, help_text='توضیح تصویر برای سئو', max_length=200, verbose_name='Alt Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='persian_cms.faproperty', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
                'db_table': 'persian_cms_property_gallery_image',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FaPropertyDescriptionHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_fa', models.CharField(max_length=100, verbose_name='عنوان')),
                ('icon', models.CharField(choices=[('fa-chart-line', 'سرمایه\u200cگذاری'), ('fa-passport', 'گلدن ویزا'), ('fa-road', 'دسترسی'), ('fa-pencil-ruler', 'طراحی'), ('fa-percent', 'بازده'), ('fa-shield-halved', 'امنیت'), ('fa-star', 'کیفیت'), ('fa-gem', 'لوکس'), ('fa-leaf', 'محیط زیست'), ('fa-sun', 'نور طبیعی')], default='fa-check-circle', max_length=30, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_highlights', to='persian_cms.faproperty', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'هایلایت توضیحات',
                'verbose_name_plural': 'هایلایت\u200cهای توضیحات',
                'db_table': 'persian_cms_property_description_highlight',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
