# Generated by Django 4.2.30 on 2026-06-03 13:51

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persian_cms', '0012_gv_landing_style_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fapropertygalleryimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='fapropertyinvestmenthighlight',
            name='property',
        ),
        migrations.RemoveField(
            model_name='fapropertylocationdistance',
            name='property',
        ),
        migrations.RemoveField(
            model_name='fapropertyprogressstep',
            name='property',
        ),
        migrations.RemoveField(
            model_name='fapropertyquickinfo',
            name='property',
        ),
        migrations.RemoveField(
            model_name='fapropertyunit',
            name='property',
        ),
        migrations.RemoveField(
            model_name='faproperty',
            name='cta_primary_text',
        ),
        migrations.RemoveField(
            model_name='faproperty',
            name='cta_secondary_text',
        ),
        migrations.RemoveField(
            model_name='faproperty',
            name='description_section_title',
        ),
        migrations.RemoveField(
            model_name='faproperty',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='faproperty',
            name='location_description_fa',
        ),
        migrations.RemoveField(
            model_name='faproperty',
            name='map_embed_url',
        ),
        migrations.RemoveField(
            model_name='faproperty',
            name='show_golden_visa_badge',
        ),
        migrations.RemoveField(
            model_name='persianmenuitem',
            name='target_page',
        ),
        migrations.AlterField(
            model_name='goldenvisalandingpage',
            name='faq_body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='HTML accordion یا لیست سوالات', verbose_name='سوالات متداول'),
        ),
        migrations.AlterField(
            model_name='goldenvisalandingpage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='توضیحات برای موتورهای جستجو (۱۵۰-۱۶۰ کاراکتر)', verbose_name='توضیحات متا'),
        ),
        migrations.AlterField(
            model_name='goldenvisalandingpage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='کلمات کلیدی با کاما جدا شوند', max_length=500, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='goldenvisalandingpage',
            name='og_image',
            field=models.ImageField(blank=True, help_text='تصویر برای اشتراک\u200cگذاری (1200x630 پیکسل)', null=True, upload_to='landing/og/', verbose_name='تصویر شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='gvfapropertyrelation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gvfapropertyrelation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='persianmenuitem',
            name='url',
            field=models.CharField(max_length=500, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='persianpage',
            name='page_type',
            field=models.CharField(choices=[('home', 'خانه'), ('about', 'درباره ما'), ('blog', 'بلاگ'), ('golden_visa', 'گلدن ویزا'), ('contact', 'تماس'), ('custom', 'سفارشی')], default='custom', max_length=30, verbose_name='نوع صفحه'),
        ),
        migrations.DeleteModel(
            name='FaPropertyDescriptionHighlight',
        ),
        migrations.DeleteModel(
            name='FaPropertyGalleryImage',
        ),
        migrations.DeleteModel(
            name='FaPropertyInvestmentHighlight',
        ),
        migrations.DeleteModel(
            name='FaPropertyLocationDistance',
        ),
        migrations.DeleteModel(
            name='FaPropertyProgressStep',
        ),
        migrations.DeleteModel(
            name='FaPropertyQuickInfo',
        ),
        migrations.DeleteModel(
            name='FaPropertyUnit',
        ),
    ]
